const mongoose = require('mongoose');
require('dotenv').config();
const ChecklistItem = require('../models/ChecklistItem');

const iloQuestions = [
  // 2.1 Key Strengths and Process Integrity
  // 2.1.1 Fact-Gathering Questions
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Key Strengths and Process Integrity',
    subsectionNumber: '2.1',
    category: 'Fact-Gathering Questions',
    categoryNumber: '2.1.1',
    questionNumber: '2.1.1.1',
    question: 'Is there any good practice/progress made or key strength in the factory?',
    progress: 100,
    completed: 1,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Key Strengths and Process Integrity',
    subsectionNumber: '2.1',
    category: 'Fact-Gathering Questions',
    categoryNumber: '2.1.1',
    questionNumber: '2.1.1.2',
    question: 'Was the assessor\'s access to the enterprise unreasonably restricted?',
    progress: 0,
    completed: 0,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Key Strengths and Process Integrity',
    subsectionNumber: '2.1',
    category: 'Fact-Gathering Questions',
    categoryNumber: '2.1.1',
    questionNumber: '2.1.1.3',
    question: 'Were documents provided in a timely manner?',
    progress: 0,
    completed: 0,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Key Strengths and Process Integrity',
    subsectionNumber: '2.1',
    category: 'Fact-Gathering Questions',
    categoryNumber: '2.1.1',
    questionNumber: '2.1.1.4',
    question: 'Number of assessment visits prior to STAR Cycle 1:',
    progress: 0,
    completed: 0,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Key Strengths and Process Integrity',
    subsectionNumber: '2.1',
    category: 'Fact-Gathering Questions',
    categoryNumber: '2.1.1',
    questionNumber: '2.1.1.5',
    question: 'How many person days were spent on the assessment visit?',
    progress: 0,
    completed: 0,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Key Strengths and Process Integrity',
    subsectionNumber: '2.1',
    category: 'Fact-Gathering Questions',
    categoryNumber: '2.1.1',
    questionNumber: '2.1.1.6',
    question: 'Provide the titles of the management staff interviewed.',
    progress: 0,
    completed: 0,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Key Strengths and Process Integrity',
    subsectionNumber: '2.1',
    category: 'Fact-Gathering Questions',
    categoryNumber: '2.1.1',
    questionNumber: '2.1.1.7',
    question: 'Briefly describe the interviews with workers/ union leaders/ shop stewards:',
    progress: 0,
    completed: 0,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Key Strengths and Process Integrity',
    subsectionNumber: '2.1',
    category: 'Fact-Gathering Questions',
    categoryNumber: '2.1.1',
    questionNumber: '2.1.1.8',
    question: 'Describe any significant concerns about process integrity.',
    progress: 0,
    completed: 0,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Key Strengths and Process Integrity',
    subsectionNumber: '2.1',
    category: 'Fact-Gathering Questions',
    categoryNumber: '2.1.1',
    questionNumber: '2.1.1.9',
    question: 'Are there any issues of concern not addressed elsewhere in the report?',
    progress: 0,
    completed: 0,
    total: 1,
  },

  // 2.2 Learning
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Learning',
    subsectionNumber: '2.2',
    category: 'Learning',
    categoryNumber: '2.2.1',
    questionNumber: '2.2.1',
    question: 'Has management consulted with elected worker representatives, including trade unions (if present) in determining the need for and scope of the assessment?',
    progress: 100,
    completed: 1,
    total: 1,
  },

  // 2.3 Child Labour
  // 2.3.1 Child Labourers
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Child Labour',
    subsectionNumber: '2.3',
    category: 'Child Labourers',
    categoryNumber: '2.3.1',
    questionNumber: '2.3.1.1',
    question: 'Have you found any workers under the age of 15?',
    progress: 100,
    completed: 1,
    total: 1,
  },

  // 2.3.2 Hazardous Work and other Worst Forms
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Child Labour',
    subsectionNumber: '2.3',
    category: 'Hazardous Work and other Worst Forms',
    categoryNumber: '2.3.2',
    questionNumber: '2.3.2.1',
    question: 'Do workers who are under age 18 perform work that is hazardous by nature?',
    progress: 100,
    completed: 1,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Child Labour',
    subsectionNumber: '2.3',
    category: 'Hazardous Work and other Worst Forms',
    categoryNumber: '2.3.2',
    questionNumber: '2.3.2.2',
    question: 'Are any workers who are under age 18 working at night, or working more than 8 hours per day (including overtime)?',
    progress: 100,
    completed: 1,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Child Labour',
    subsectionNumber: '2.3',
    category: 'Hazardous Work and other Worst Forms',
    categoryNumber: '2.3.2',
    questionNumber: '2.3.2.3',
    question: 'Does the employer subject any workers under age 18 to the unconditional worst forms of child labour?',
    progress: 100,
    completed: 1,
    total: 1,
  },

  // 2.3.3 Documentation and Protection of Young Workers
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Child Labour',
    subsectionNumber: '2.3',
    category: 'Documentation and Protection of Young Workers',
    categoryNumber: '2.3.3',
    questionNumber: '2.3.3.1',
    question: 'Does the employer reliably verify the age of workers prior to hiring?',
    progress: 100,
    completed: 1,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Child Labour',
    subsectionNumber: '2.3',
    category: 'Documentation and Protection of Young Workers',
    categoryNumber: '2.3.3',
    questionNumber: '2.3.3.2',
    question: 'Does the employer keep a register and get consent from the guardians of workers under 18 years of age?',
    progress: 100,
    completed: 1,
    total: 1,
  },

  // 2.4 Discrimination
  // 2.4.1 Race and Origin
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Discrimination',
    subsectionNumber: '2.4',
    category: 'Race and Origin',
    categoryNumber: '2.4.1',
    questionNumber: '2.4.1.1',
    question: 'Do recruitment materials such as job announcements or job application forms refer to the applicant\'s race, colour or origin?',
    progress: 100,
    completed: 1,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Discrimination',
    subsectionNumber: '2.4',
    category: 'Race and Origin',
    categoryNumber: '2.4.1',
    questionNumber: '2.4.1.2',
    question: 'Is an applicant\'s race, colour or origin a factor in hiring decisions?',
    progress: 100,
    completed: 1,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Discrimination',
    subsectionNumber: '2.4',
    category: 'Race and Origin',
    categoryNumber: '2.4.1',
    questionNumber: '2.4.1.3',
    question: 'Is race, colour or origin a factor in decisions regarding conditions of work?',
    progress: 100,
    completed: 1,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Discrimination',
    subsectionNumber: '2.4',
    category: 'Race and Origin',
    categoryNumber: '2.4.1',
    questionNumber: '2.4.1.4',
    question: 'Is race, colour or origin a factor in decisions regarding pay?',
    progress: 100,
    completed: 1,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Discrimination',
    subsectionNumber: '2.4',
    category: 'Race and Origin',
    categoryNumber: '2.4.1',
    questionNumber: '2.4.1.5',
    question: 'Is race, colour or origin a factor in decisions regarding opportunities for promotion or access to training?',
    progress: 100,
    completed: 1,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Discrimination',
    subsectionNumber: '2.4',
    category: 'Race and Origin',
    categoryNumber: '2.4.1',
    questionNumber: '2.4.1.6',
    question: 'Is there harassment of workers on the basis of race, colour or origin?',
    progress: 100,
    completed: 1,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Discrimination',
    subsectionNumber: '2.4',
    category: 'Race and Origin',
    categoryNumber: '2.4.1',
    questionNumber: '2.4.1.7',
    question: 'Is race, colour or origin a factor in the employer\'s decisions regarding termination or retirement of workers?',
    progress: 100,
    completed: 1,
    total: 1,
  },

  // 2.4.2 Religion and Political Opinion
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Discrimination',
    subsectionNumber: '2.4',
    category: 'Religion and Political Opinion',
    categoryNumber: '2.4.2',
    questionNumber: '2.4.2.1',
    question: 'Do recruitment materials such as job announcements or job application forms refer to the applicant\'s religion or political opinion?',
    progress: 100,
    completed: 1,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Discrimination',
    subsectionNumber: '2.4',
    category: 'Religion and Political Opinion',
    categoryNumber: '2.4.2',
    questionNumber: '2.4.2.2',
    question: 'Is an applicant\'s religion or political opinion a factor in hiring decisions?',
    progress: 100,
    completed: 1,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Discrimination',
    subsectionNumber: '2.4',
    category: 'Religion and Political Opinion',
    categoryNumber: '2.4.2',
    questionNumber: '2.4.2.3',
    question: 'Is religion or political opinion a factor in decisions regarding conditions of work?',
    progress: 100,
    completed: 1,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Discrimination',
    subsectionNumber: '2.4',
    category: 'Religion and Political Opinion',
    categoryNumber: '2.4.2',
    questionNumber: '2.4.2.4',
    question: 'Is religion or political opinion a factor in decisions regarding pay?',
    progress: 100,
    completed: 1,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Discrimination',
    subsectionNumber: '2.4',
    category: 'Religion and Political Opinion',
    categoryNumber: '2.4.2',
    questionNumber: '2.4.2.5',
    question: 'Is religion or political opinion a factor in decisions regarding opportunities for promotion or access to training?',
    progress: 100,
    completed: 1,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Discrimination',
    subsectionNumber: '2.4',
    category: 'Religion and Political Opinion',
    categoryNumber: '2.4.2',
    questionNumber: '2.4.2.6',
    question: 'Is there harassment of workers on the basis of religion or political opinion?',
    progress: 100,
    completed: 1,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Discrimination',
    subsectionNumber: '2.4',
    category: 'Religion and Political Opinion',
    categoryNumber: '2.4.2',
    questionNumber: '2.4.2.7',
    question: 'Is religion or political opinion a factor in the employer\'s decisions regarding termination or retirement of workers?',
    progress: 100,
    completed: 1,
    total: 1,
  },

  // 2.4.3 Gender
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Discrimination',
    subsectionNumber: '2.4',
    category: 'Gender',
    categoryNumber: '2.4.3',
    questionNumber: '2.4.3.1',
    question: 'Do job announcements refer to the applicant\'s gender?',
    progress: 100,
    completed: 1,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Discrimination',
    subsectionNumber: '2.4',
    category: 'Gender',
    categoryNumber: '2.4.3',
    questionNumber: '2.4.3.2',
    question: 'Is an applicant\'s gender a factor in hiring decisions?',
    progress: 100,
    completed: 1,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Discrimination',
    subsectionNumber: '2.4',
    category: 'Gender',
    categoryNumber: '2.4.3',
    questionNumber: '2.4.3.3',
    question: 'Is gender a factor in decisions regarding conditions of work?',
    progress: 100,
    completed: 1,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Discrimination',
    subsectionNumber: '2.4',
    category: 'Gender',
    categoryNumber: '2.4.3',
    questionNumber: '2.4.3.4',
    question: 'Is gender a factor in decisions regarding pay?',
    progress: 100,
    completed: 1,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Discrimination',
    subsectionNumber: '2.4',
    category: 'Gender',
    categoryNumber: '2.4.3',
    questionNumber: '2.4.3.5',
    question: 'Is gender a factor in decisions regarding opportunities for promotion or access to training?',
    progress: 100,
    completed: 1,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Discrimination',
    subsectionNumber: '2.4',
    category: 'Gender',
    categoryNumber: '2.4.3',
    questionNumber: '2.4.3.6',
    question: 'Is gender a factor in the employer\'s decisions regarding termination or retirement of workers?',
    progress: 100,
    completed: 1,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Discrimination',
    subsectionNumber: '2.4',
    category: 'Gender',
    categoryNumber: '2.4.3',
    questionNumber: '2.4.3.7',
    question: 'Are workers subject to sexual harassment?',
    progress: 100,
    completed: 1,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Discrimination',
    subsectionNumber: '2.4',
    category: 'Gender',
    categoryNumber: '2.4.3',
    questionNumber: '2.4.3.8',
    question: 'Does the employer require pregnancy tests or the use of contraceptives as a condition of employment?',
    progress: 100,
    completed: 1,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Discrimination',
    subsectionNumber: '2.4',
    category: 'Gender',
    categoryNumber: '2.4.3',
    questionNumber: '2.4.3.9',
    question: 'The maternity leave was excluded from workers\' period of continuous service?',
    progress: 100,
    completed: 1,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Discrimination',
    subsectionNumber: '2.4',
    category: 'Gender',
    categoryNumber: '2.4.3',
    questionNumber: '2.4.3.10',
    question: 'Does the employer change the employment status, position, wages, benefits or seniority of workers during or after maternity leave?',
    progress: 100,
    completed: 1,
    total: 1,
  },

  // 2.4.4 Other Grounds
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Discrimination',
    subsectionNumber: '2.4',
    category: 'Other Grounds',
    categoryNumber: '2.4.4',
    questionNumber: '2.4.4.1',
    question: 'Is an applicant\'s real or perceived HIV/AIDS status a factor in hiring decisions?',
    progress: 100,
    completed: 1,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Discrimination',
    subsectionNumber: '2.4',
    category: 'Other Grounds',
    categoryNumber: '2.4.4',
    questionNumber: '2.4.4.2',
    question: 'Are HIV/AIDS tests required at hiring or at any time during employment?',
    progress: 100,
    completed: 1,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Discrimination',
    subsectionNumber: '2.4',
    category: 'Other Grounds',
    categoryNumber: '2.4.4',
    questionNumber: '2.4.4.3',
    question: 'Is HIV/AIDS status a factor in decisions regarding conditions of work?',
    progress: 100,
    completed: 1,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Discrimination',
    subsectionNumber: '2.4',
    category: 'Other Grounds',
    categoryNumber: '2.4.4',
    questionNumber: '2.4.4.4',
    question: 'Is HIV/AIDS status a factor in decisions regarding pay?',
    progress: 100,
    completed: 1,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Discrimination',
    subsectionNumber: '2.4',
    category: 'Other Grounds',
    categoryNumber: '2.4.4',
    questionNumber: '2.4.4.5',
    question: 'Is HIV/AIDS status a factor in decisions regarding opportunities for promotion or access to training?',
    progress: 100,
    completed: 1,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Discrimination',
    subsectionNumber: '2.4',
    category: 'Other Grounds',
    categoryNumber: '2.4.4',
    questionNumber: '2.4.4.6',
    question: 'Is there harassment of workers on the basis of real or perceived HIV/AIDS status?',
    progress: 100,
    completed: 1,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Discrimination',
    subsectionNumber: '2.4',
    category: 'Other Grounds',
    categoryNumber: '2.4.4',
    questionNumber: '2.4.4.7',
    question: 'Is a worker\'s real or perceived HIV/AIDS status a factor in the employer\'s decisions regarding termination or retirement?',
    progress: 100,
    completed: 1,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Discrimination',
    subsectionNumber: '2.4',
    category: 'Other Grounds',
    categoryNumber: '2.4.4',
    questionNumber: '2.4.4.8',
    question: 'Are disabled persons who apply for work evaluated according to their ability to perform the job?',
    progress: 100,
    completed: 1,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Discrimination',
    subsectionNumber: '2.4',
    category: 'Other Grounds',
    categoryNumber: '2.4.4',
    questionNumber: '2.4.4.9',
    question: 'Has the employer taken steps to reasonably accommodate physically disabled persons?',
    progress: 100,
    completed: 1,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Discrimination',
    subsectionNumber: '2.4',
    category: 'Other Grounds',
    categoryNumber: '2.4.4',
    questionNumber: '2.4.4.10',
    question: 'Is disability a factor in decisions regarding conditions of work?',
    progress: 100,
    completed: 1,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Discrimination',
    subsectionNumber: '2.4',
    category: 'Other Grounds',
    categoryNumber: '2.4.4',
    questionNumber: '2.4.4.11',
    question: 'Is disability a factor in decisions regarding pay?',
    progress: 100,
    completed: 1,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Discrimination',
    subsectionNumber: '2.4',
    category: 'Other Grounds',
    categoryNumber: '2.4.4',
    questionNumber: '2.4.4.12',
    question: 'Is disability a factor in decisions regarding opportunities for promotion or access to training?',
    progress: 100,
    completed: 1,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Discrimination',
    subsectionNumber: '2.4',
    category: 'Other Grounds',
    categoryNumber: '2.4.4',
    questionNumber: '2.4.4.13',
    question: 'Is there harassment of workers on the basis of disability?',
    progress: 100,
    completed: 1,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Discrimination',
    subsectionNumber: '2.4',
    category: 'Other Grounds',
    categoryNumber: '2.4.4',
    questionNumber: '2.4.4.14',
    question: 'Is the employer\'s decisions regarding termination or retirement a factor of disability?',
    progress: 100,
    completed: 1,
    total: 1,
  },

  // 2.5 Forced Labour (categories collapsed in source — headers only with counts)
  // 2.5.1 Coercion — 100% (8/8)
  // 2.5.2 Bonded Labour — 100% (1/1)
  // 2.5.3 Forced Labour and Overtime — 100% (1/1)
  // 2.5.4 Prison Labour — 100% (1/1)
  // TODO: expand 2.5 categories to add individual question text

  // 2.6 Freedom of Association and Collective Bargaining
  // 2.6.1 Fact-Gathering Questions
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Freedom of Association and Collective Bargaining',
    subsectionNumber: '2.6',
    category: 'Fact-Gathering Questions',
    categoryNumber: '2.6.1',
    questionNumber: '2.6.1.1',
    question: 'What percentage of workers are union members?',
    progress: 0,
    completed: 0,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Freedom of Association and Collective Bargaining',
    subsectionNumber: '2.6',
    category: 'Fact-Gathering Questions',
    categoryNumber: '2.6.1',
    questionNumber: '2.6.1.2',
    question: 'How many active registered unions are there in the factory?',
    progress: 100,
    completed: 1,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Freedom of Association and Collective Bargaining',
    subsectionNumber: '2.6',
    category: 'Fact-Gathering Questions',
    categoryNumber: '2.6.1',
    questionNumber: '2.6.1.3',
    question: 'For each union, please provide name, last registration date, the number of union leaders (man, women), total number of members (men, women).',
    progress: 100,
    completed: 1,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Freedom of Association and Collective Bargaining',
    subsectionNumber: '2.6',
    category: 'Fact-Gathering Questions',
    categoryNumber: '2.6.1',
    questionNumber: '2.6.1.4',
    question: 'How many collective bargaining agreements are in effect in the factory?',
    progress: 100,
    completed: 1,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Freedom of Association and Collective Bargaining',
    subsectionNumber: '2.6',
    category: 'Fact-Gathering Questions',
    categoryNumber: '2.6.1',
    questionNumber: '2.6.1.5',
    question: 'For each CBA, please indicate the parties, the percentage of the workforce covered, the duration of the agreement.',
    progress: 100,
    completed: 1,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Freedom of Association and Collective Bargaining',
    subsectionNumber: '2.6',
    category: 'Fact-Gathering Questions',
    categoryNumber: '2.6.1',
    questionNumber: '2.6.1.6',
    question: 'How many strikes have there been since the last visit?',
    progress: 0,
    completed: 0,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Freedom of Association and Collective Bargaining',
    subsectionNumber: '2.6',
    category: 'Fact-Gathering Questions',
    categoryNumber: '2.6.1',
    questionNumber: '2.6.1.7',
    question: 'For each strike, please indicate the reason workers went on strike, whether the strike resulted in violence, the duration of the strike.',
    progress: 100,
    completed: 1,
    total: 1,
  },
];

async function seed() {
  try {
    await mongoose.connect(process.env.MONGODB_URI);
    console.log('Connected to MongoDB');

    await ChecklistItem.deleteMany({ section: 'ILO' });
    console.log('Cleared existing ILO checklist items');

    const result = await ChecklistItem.insertMany(iloQuestions);
    console.log(`Inserted ${result.length} checklist items`);

    await mongoose.disconnect();
    console.log('Done!');
  } catch (err) {
    console.error('Seed error:', err);
    process.exit(1);
  }
}

seed();
