const mongoose = require('mongoose');
require('dotenv').config();
const ChecklistItem = require('../models/ChecklistItem');

const iloQuestions = [
  // 2.1 Key Strengths and Process Integrity
  // 2.1.1 Fact-Gathering Questions
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Key Strengths and Process Integrity',
    subsectionNumber: '2.1',
    category: 'Fact-Gathering Questions',
    categoryNumber: '2.1.1',
    questionNumber: '2.1.1.1',
    question: 'Is there any good practice/progress made or key strength in the factory?',
    progress: 100,
    completed: 1,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Key Strengths and Process Integrity',
    subsectionNumber: '2.1',
    category: 'Fact-Gathering Questions',
    categoryNumber: '2.1.1',
    questionNumber: '2.1.1.2',
    question: 'Was the assessor\'s access to the enterprise unreasonably restricted?',
    progress: 0,
    completed: 0,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Key Strengths and Process Integrity',
    subsectionNumber: '2.1',
    category: 'Fact-Gathering Questions',
    categoryNumber: '2.1.1',
    questionNumber: '2.1.1.3',
    question: 'Were documents provided in a timely manner?',
    progress: 0,
    completed: 0,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Key Strengths and Process Integrity',
    subsectionNumber: '2.1',
    category: 'Fact-Gathering Questions',
    categoryNumber: '2.1.1',
    questionNumber: '2.1.1.4',
    question: 'Number of assessment visits prior to STAR Cycle 1:',
    progress: 0,
    completed: 0,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Key Strengths and Process Integrity',
    subsectionNumber: '2.1',
    category: 'Fact-Gathering Questions',
    categoryNumber: '2.1.1',
    questionNumber: '2.1.1.5',
    question: 'How many person days were spent on the assessment visit?',
    progress: 0,
    completed: 0,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Key Strengths and Process Integrity',
    subsectionNumber: '2.1',
    category: 'Fact-Gathering Questions',
    categoryNumber: '2.1.1',
    questionNumber: '2.1.1.6',
    question: 'Provide the titles of the management staff interviewed.',
    progress: 0,
    completed: 0,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Key Strengths and Process Integrity',
    subsectionNumber: '2.1',
    category: 'Fact-Gathering Questions',
    categoryNumber: '2.1.1',
    questionNumber: '2.1.1.7',
    question: 'Briefly describe the interviews with workers/ union leaders/ shop stewards:',
    progress: 0,
    completed: 0,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Key Strengths and Process Integrity',
    subsectionNumber: '2.1',
    category: 'Fact-Gathering Questions',
    categoryNumber: '2.1.1',
    questionNumber: '2.1.1.8',
    question: 'Describe any significant concerns about process integrity.',
    progress: 0,
    completed: 0,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Key Strengths and Process Integrity',
    subsectionNumber: '2.1',
    category: 'Fact-Gathering Questions',
    categoryNumber: '2.1.1',
    questionNumber: '2.1.1.9',
    question: 'Are there any issues of concern not addressed elsewhere in the report?',
    progress: 0,
    completed: 0,
    total: 1,
  },

  // 2.2 Learning
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Learning',
    subsectionNumber: '2.2',
    category: 'Learning',
    categoryNumber: '2.2.1',
    questionNumber: '2.2.1',
    question: 'Has management consulted with elected worker representatives, including trade unions (if present) in determining the need for and scope of the assessment?',
    progress: 100,
    completed: 1,
    total: 1,
  },

  // 2.3 Child Labour
  // 2.3.1 Child Labourers
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Child Labour',
    subsectionNumber: '2.3',
    category: 'Child Labourers',
    categoryNumber: '2.3.1',
    questionNumber: '2.3.1.1',
    question: 'Have you found any workers under the age of 15?',
    progress: 100,
    completed: 1,
    total: 1,
  },

  // 2.3.2 Hazardous Work and other Worst Forms
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Child Labour',
    subsectionNumber: '2.3',
    category: 'Hazardous Work and other Worst Forms',
    categoryNumber: '2.3.2',
    questionNumber: '2.3.2.1',
    question: 'Do workers who are under age 18 perform work that is hazardous by nature?',
    progress: 100,
    completed: 1,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Child Labour',
    subsectionNumber: '2.3',
    category: 'Hazardous Work and other Worst Forms',
    categoryNumber: '2.3.2',
    questionNumber: '2.3.2.2',
    question: 'Are any workers who are under age 18 working at night, or working more than 8 hours per day (including overtime)?',
    progress: 100,
    completed: 1,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Child Labour',
    subsectionNumber: '2.3',
    category: 'Hazardous Work and other Worst Forms',
    categoryNumber: '2.3.2',
    questionNumber: '2.3.2.3',
    question: 'Does the employer subject any workers under age 18 to the unconditional worst forms of child labour?',
    progress: 100,
    completed: 1,
    total: 1,
  },

  // 2.3.3 Documentation and Protection of Young Workers
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Child Labour',
    subsectionNumber: '2.3',
    category: 'Documentation and Protection of Young Workers',
    categoryNumber: '2.3.3',
    questionNumber: '2.3.3.1',
    question: 'Does the employer reliably verify the age of workers prior to hiring?',
    progress: 100,
    completed: 1,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Child Labour',
    subsectionNumber: '2.3',
    category: 'Documentation and Protection of Young Workers',
    categoryNumber: '2.3.3',
    questionNumber: '2.3.3.2',
    question: 'Does the employer keep a register and get consent from the guardians of workers under 18 years of age?',
    progress: 100,
    completed: 1,
    total: 1,
  },

  // 2.4 Discrimination
  // 2.4.1 Race and Origin
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Discrimination',
    subsectionNumber: '2.4',
    category: 'Race and Origin',
    categoryNumber: '2.4.1',
    questionNumber: '2.4.1.1',
    question: 'Do recruitment materials such as job announcements or job application forms refer to the applicant\'s race, colour or origin?',
    progress: 100,
    completed: 1,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Discrimination',
    subsectionNumber: '2.4',
    category: 'Race and Origin',
    categoryNumber: '2.4.1',
    questionNumber: '2.4.1.2',
    question: 'Is an applicant\'s race, colour or origin a factor in hiring decisions?',
    progress: 100,
    completed: 1,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Discrimination',
    subsectionNumber: '2.4',
    category: 'Race and Origin',
    categoryNumber: '2.4.1',
    questionNumber: '2.4.1.3',
    question: 'Is race, colour or origin a factor in decisions regarding conditions of work?',
    progress: 100,
    completed: 1,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Discrimination',
    subsectionNumber: '2.4',
    category: 'Race and Origin',
    categoryNumber: '2.4.1',
    questionNumber: '2.4.1.4',
    question: 'Is race, colour or origin a factor in decisions regarding pay?',
    progress: 100,
    completed: 1,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Discrimination',
    subsectionNumber: '2.4',
    category: 'Race and Origin',
    categoryNumber: '2.4.1',
    questionNumber: '2.4.1.5',
    question: 'Is race, colour or origin a factor in decisions regarding opportunities for promotion or access to training?',
    progress: 100,
    completed: 1,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Discrimination',
    subsectionNumber: '2.4',
    category: 'Race and Origin',
    categoryNumber: '2.4.1',
    questionNumber: '2.4.1.6',
    question: 'Is there harassment of workers on the basis of race, colour or origin?',
    progress: 100,
    completed: 1,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Discrimination',
    subsectionNumber: '2.4',
    category: 'Race and Origin',
    categoryNumber: '2.4.1',
    questionNumber: '2.4.1.7',
    question: 'Is race, colour or origin a factor in the employer\'s decisions regarding termination or retirement of workers?',
    progress: 100,
    completed: 1,
    total: 1,
  },

  // 2.4.2 Religion and Political Opinion
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Discrimination',
    subsectionNumber: '2.4',
    category: 'Religion and Political Opinion',
    categoryNumber: '2.4.2',
    questionNumber: '2.4.2.1',
    question: 'Do recruitment materials such as job announcements or job application forms refer to the applicant\'s religion or political opinion?',
    progress: 100,
    completed: 1,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Discrimination',
    subsectionNumber: '2.4',
    category: 'Religion and Political Opinion',
    categoryNumber: '2.4.2',
    questionNumber: '2.4.2.2',
    question: 'Is an applicant\'s religion or political opinion a factor in hiring decisions?',
    progress: 100,
    completed: 1,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Discrimination',
    subsectionNumber: '2.4',
    category: 'Religion and Political Opinion',
    categoryNumber: '2.4.2',
    questionNumber: '2.4.2.3',
    question: 'Is religion or political opinion a factor in decisions regarding conditions of work?',
    progress: 100,
    completed: 1,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Discrimination',
    subsectionNumber: '2.4',
    category: 'Religion and Political Opinion',
    categoryNumber: '2.4.2',
    questionNumber: '2.4.2.4',
    question: 'Is religion or political opinion a factor in decisions regarding pay?',
    progress: 100,
    completed: 1,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Discrimination',
    subsectionNumber: '2.4',
    category: 'Religion and Political Opinion',
    categoryNumber: '2.4.2',
    questionNumber: '2.4.2.5',
    question: 'Is religion or political opinion a factor in decisions regarding opportunities for promotion or access to training?',
    progress: 100,
    completed: 1,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Discrimination',
    subsectionNumber: '2.4',
    category: 'Religion and Political Opinion',
    categoryNumber: '2.4.2',
    questionNumber: '2.4.2.6',
    question: 'Is there harassment of workers on the basis of religion or political opinion?',
    progress: 100,
    completed: 1,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Discrimination',
    subsectionNumber: '2.4',
    category: 'Religion and Political Opinion',
    categoryNumber: '2.4.2',
    questionNumber: '2.4.2.7',
    question: 'Is religion or political opinion a factor in the employer\'s decisions regarding termination or retirement of workers?',
    progress: 100,
    completed: 1,
    total: 1,
  },

  // 2.4.3 Gender
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Discrimination',
    subsectionNumber: '2.4',
    category: 'Gender',
    categoryNumber: '2.4.3',
    questionNumber: '2.4.3.1',
    question: 'Do job announcements refer to the applicant\'s gender?',
    progress: 100,
    completed: 1,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Discrimination',
    subsectionNumber: '2.4',
    category: 'Gender',
    categoryNumber: '2.4.3',
    questionNumber: '2.4.3.2',
    question: 'Is an applicant\'s gender a factor in hiring decisions?',
    progress: 100,
    completed: 1,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Discrimination',
    subsectionNumber: '2.4',
    category: 'Gender',
    categoryNumber: '2.4.3',
    questionNumber: '2.4.3.3',
    question: 'Is gender a factor in decisions regarding conditions of work?',
    progress: 100,
    completed: 1,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Discrimination',
    subsectionNumber: '2.4',
    category: 'Gender',
    categoryNumber: '2.4.3',
    questionNumber: '2.4.3.4',
    question: 'Is gender a factor in decisions regarding pay?',
    progress: 100,
    completed: 1,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Discrimination',
    subsectionNumber: '2.4',
    category: 'Gender',
    categoryNumber: '2.4.3',
    questionNumber: '2.4.3.5',
    question: 'Is gender a factor in decisions regarding opportunities for promotion or access to training?',
    progress: 100,
    completed: 1,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Discrimination',
    subsectionNumber: '2.4',
    category: 'Gender',
    categoryNumber: '2.4.3',
    questionNumber: '2.4.3.6',
    question: 'Is gender a factor in the employer\'s decisions regarding termination or retirement of workers?',
    progress: 100,
    completed: 1,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Discrimination',
    subsectionNumber: '2.4',
    category: 'Gender',
    categoryNumber: '2.4.3',
    questionNumber: '2.4.3.7',
    question: 'Are workers subject to sexual harassment?',
    progress: 100,
    completed: 1,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Discrimination',
    subsectionNumber: '2.4',
    category: 'Gender',
    categoryNumber: '2.4.3',
    questionNumber: '2.4.3.8',
    question: 'Does the employer require pregnancy tests or the use of contraceptives as a condition of employment?',
    progress: 100,
    completed: 1,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Discrimination',
    subsectionNumber: '2.4',
    category: 'Gender',
    categoryNumber: '2.4.3',
    questionNumber: '2.4.3.9',
    question: 'The maternity leave was excluded from workers\' period of continuous service?',
    progress: 100,
    completed: 1,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Discrimination',
    subsectionNumber: '2.4',
    category: 'Gender',
    categoryNumber: '2.4.3',
    questionNumber: '2.4.3.10',
    question: 'Does the employer change the employment status, position, wages, benefits or seniority of workers during or after maternity leave?',
    progress: 100,
    completed: 1,
    total: 1,
  },

  // 2.4.4 Other Grounds
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Discrimination',
    subsectionNumber: '2.4',
    category: 'Other Grounds',
    categoryNumber: '2.4.4',
    questionNumber: '2.4.4.1',
    question: 'Is an applicant\'s real or perceived HIV/AIDS status a factor in hiring decisions?',
    progress: 100,
    completed: 1,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Discrimination',
    subsectionNumber: '2.4',
    category: 'Other Grounds',
    categoryNumber: '2.4.4',
    questionNumber: '2.4.4.2',
    question: 'Are HIV/AIDS tests required at hiring or at any time during employment?',
    progress: 100,
    completed: 1,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Discrimination',
    subsectionNumber: '2.4',
    category: 'Other Grounds',
    categoryNumber: '2.4.4',
    questionNumber: '2.4.4.3',
    question: 'Is HIV/AIDS status a factor in decisions regarding conditions of work?',
    progress: 100,
    completed: 1,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Discrimination',
    subsectionNumber: '2.4',
    category: 'Other Grounds',
    categoryNumber: '2.4.4',
    questionNumber: '2.4.4.4',
    question: 'Is HIV/AIDS status a factor in decisions regarding pay?',
    progress: 100,
    completed: 1,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Discrimination',
    subsectionNumber: '2.4',
    category: 'Other Grounds',
    categoryNumber: '2.4.4',
    questionNumber: '2.4.4.5',
    question: 'Is HIV/AIDS status a factor in decisions regarding opportunities for promotion or access to training?',
    progress: 100,
    completed: 1,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Discrimination',
    subsectionNumber: '2.4',
    category: 'Other Grounds',
    categoryNumber: '2.4.4',
    questionNumber: '2.4.4.6',
    question: 'Is there harassment of workers on the basis of real or perceived HIV/AIDS status?',
    progress: 100,
    completed: 1,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Discrimination',
    subsectionNumber: '2.4',
    category: 'Other Grounds',
    categoryNumber: '2.4.4',
    questionNumber: '2.4.4.7',
    question: 'Is a worker\'s real or perceived HIV/AIDS status a factor in the employer\'s decisions regarding termination or retirement?',
    progress: 100,
    completed: 1,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Discrimination',
    subsectionNumber: '2.4',
    category: 'Other Grounds',
    categoryNumber: '2.4.4',
    questionNumber: '2.4.4.8',
    question: 'Are disabled persons who apply for work evaluated according to their ability to perform the job?',
    progress: 100,
    completed: 1,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Discrimination',
    subsectionNumber: '2.4',
    category: 'Other Grounds',
    categoryNumber: '2.4.4',
    questionNumber: '2.4.4.9',
    question: 'Has the employer taken steps to reasonably accommodate physically disabled persons?',
    progress: 100,
    completed: 1,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Discrimination',
    subsectionNumber: '2.4',
    category: 'Other Grounds',
    categoryNumber: '2.4.4',
    questionNumber: '2.4.4.10',
    question: 'Is disability a factor in decisions regarding conditions of work?',
    progress: 100,
    completed: 1,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Discrimination',
    subsectionNumber: '2.4',
    category: 'Other Grounds',
    categoryNumber: '2.4.4',
    questionNumber: '2.4.4.11',
    question: 'Is disability a factor in decisions regarding pay?',
    progress: 100,
    completed: 1,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Discrimination',
    subsectionNumber: '2.4',
    category: 'Other Grounds',
    categoryNumber: '2.4.4',
    questionNumber: '2.4.4.12',
    question: 'Is disability a factor in decisions regarding opportunities for promotion or access to training?',
    progress: 100,
    completed: 1,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Discrimination',
    subsectionNumber: '2.4',
    category: 'Other Grounds',
    categoryNumber: '2.4.4',
    questionNumber: '2.4.4.13',
    question: 'Is there harassment of workers on the basis of disability?',
    progress: 100,
    completed: 1,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Discrimination',
    subsectionNumber: '2.4',
    category: 'Other Grounds',
    categoryNumber: '2.4.4',
    questionNumber: '2.4.4.14',
    question: 'Is the employer\'s decisions regarding termination or retirement a factor of disability?',
    progress: 100,
    completed: 1,
    total: 1,
  },

  // 2.5 Forced Labour (categories collapsed in source — headers only with counts)
  // 2.5.1 Coercion — 100% (8/8)
  // 2.5.2 Bonded Labour — 100% (1/1)
  // 2.5.3 Forced Labour and Overtime — 100% (1/1)
  // 2.5.4 Prison Labour — 100% (1/1)
  // TODO: expand 2.5 categories to add individual question text

  // 2.6 Freedom of Association and Collective Bargaining
  // 2.6.1 Fact-Gathering Questions
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Freedom of Association and Collective Bargaining',
    subsectionNumber: '2.6',
    category: 'Fact-Gathering Questions',
    categoryNumber: '2.6.1',
    questionNumber: '2.6.1.1',
    question: 'What percentage of workers are union members?',
    progress: 0,
    completed: 0,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Freedom of Association and Collective Bargaining',
    subsectionNumber: '2.6',
    category: 'Fact-Gathering Questions',
    categoryNumber: '2.6.1',
    questionNumber: '2.6.1.2',
    question: 'How many active registered unions are there in the factory?',
    progress: 100,
    completed: 1,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Freedom of Association and Collective Bargaining',
    subsectionNumber: '2.6',
    category: 'Fact-Gathering Questions',
    categoryNumber: '2.6.1',
    questionNumber: '2.6.1.3',
    question: 'For each union, please provide name, last registration date, the number of union leaders (man, women), total number of members (men, women).',
    progress: 100,
    completed: 1,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Freedom of Association and Collective Bargaining',
    subsectionNumber: '2.6',
    category: 'Fact-Gathering Questions',
    categoryNumber: '2.6.1',
    questionNumber: '2.6.1.4',
    question: 'How many collective bargaining agreements are in effect in the factory?',
    progress: 100,
    completed: 1,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Freedom of Association and Collective Bargaining',
    subsectionNumber: '2.6',
    category: 'Fact-Gathering Questions',
    categoryNumber: '2.6.1',
    questionNumber: '2.6.1.5',
    question: 'For each CBA, please indicate the parties, the percentage of the workforce covered, the duration of the agreement.',
    progress: 100,
    completed: 1,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Freedom of Association and Collective Bargaining',
    subsectionNumber: '2.6',
    category: 'Fact-Gathering Questions',
    categoryNumber: '2.6.1',
    questionNumber: '2.6.1.6',
    question: 'How many strikes have there been since the last visit?',
    progress: 0,
    completed: 0,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Freedom of Association and Collective Bargaining',
    subsectionNumber: '2.6',
    category: 'Fact-Gathering Questions',
    categoryNumber: '2.6.1',
    questionNumber: '2.6.1.7',
    question: 'For each strike, please indicate the reason workers went on strike, whether the strike resulted in violence, the duration of the strike.',
    progress: 100,
    completed: 1,
    total: 1,
  },

  // 2.6.2 Freedom to Associate
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Freedom of Association and Collective Bargaining',
    subsectionNumber: '2.6',
    category: 'Freedom to Associate',
    categoryNumber: '2.6.2',
    questionNumber: '2.6.2.1',
    question: 'Can workers freely form and join a union?',
    progress: 100,
    completed: 1,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Freedom of Association and Collective Bargaining',
    subsectionNumber: '2.6',
    category: 'Freedom to Associate',
    categoryNumber: '2.6.2',
    questionNumber: '2.6.2.2',
    question: 'Can the union(s) freely form and join federations and confederations of their choice?',
    progress: 100,
    completed: 1,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Freedom of Association and Collective Bargaining',
    subsectionNumber: '2.6',
    category: 'Freedom to Associate',
    categoryNumber: '2.6.2',
    questionNumber: '2.6.2.3',
    question: 'Does the employer require workers to join a union?',
    progress: 100,
    completed: 1,
    total: 1,
  },

  // 2.6.3 Union Operations
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Freedom of Association and Collective Bargaining',
    subsectionNumber: '2.6',
    category: 'Union Operations',
    categoryNumber: '2.6.3',
    questionNumber: '2.6.3.1',
    question: 'Do union representatives have access to workers in the workplace?',
    progress: 100,
    completed: 1,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Freedom of Association and Collective Bargaining',
    subsectionNumber: '2.6',
    category: 'Union Operations',
    categoryNumber: '2.6.3',
    questionNumber: '2.6.3.2',
    question: 'Does the employer deduct union dues from wages when workers request this in writing?',
    progress: 100,
    completed: 1,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Freedom of Association and Collective Bargaining',
    subsectionNumber: '2.6',
    category: 'Union Operations',
    categoryNumber: '2.6.3',
    questionNumber: '2.6.3.3',
    question: 'Does the employer provide a place to post the names, positions, and activities of the union leaders?',
    progress: 100,
    completed: 1,
    total: 1,
  },

  // 2.6.4 Interference and Discrimination
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Freedom of Association and Collective Bargaining',
    subsectionNumber: '2.6',
    category: 'Interference and Discrimination',
    categoryNumber: '2.6.4',
    questionNumber: '2.6.4.1',
    question: 'Are workers free to meet without management present?',
    progress: 100,
    completed: 1,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Freedom of Association and Collective Bargaining',
    subsectionNumber: '2.6',
    category: 'Interference and Discrimination',
    categoryNumber: '2.6.4',
    questionNumber: '2.6.4.2',
    question: 'If there is more than one union, does the employer treat them equally?',
    progress: 100,
    completed: 1,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Freedom of Association and Collective Bargaining',
    subsectionNumber: '2.6',
    category: 'Interference and Discrimination',
    categoryNumber: '2.6.4',
    questionNumber: '2.6.4.3',
    question: 'Is the employer involved in union decision making, the formation of the constitution and rules, in union activities or the administration of the union?',
    progress: 100,
    completed: 0,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Freedom of Association and Collective Bargaining',
    subsectionNumber: '2.6',
    category: 'Interference and Discrimination',
    categoryNumber: '2.6.4',
    questionNumber: '2.6.4.4',
    question: 'Does the employer provide incentives to workers to keep them from joining a union or engaging in union activities?',
    progress: 100,
    completed: 0,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Freedom of Association and Collective Bargaining',
    subsectionNumber: '2.6',
    category: 'Interference and Discrimination',
    categoryNumber: '2.6.4',
    questionNumber: '2.6.4.5',
    question: 'Is a job applicant\'s union membership or union activities a factor in hiring decisions?',
    progress: 100,
    completed: 1,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Freedom of Association and Collective Bargaining',
    subsectionNumber: '2.6',
    category: 'Interference and Discrimination',
    categoryNumber: '2.6.4',
    questionNumber: '2.6.4.6',
    question: 'Has the employer taken steps to manipulate the union or to bring the union(s) under its control?',
    progress: 100,
    completed: 1,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Freedom of Association and Collective Bargaining',
    subsectionNumber: '2.6',
    category: 'Interference and Discrimination',
    categoryNumber: '2.6.4',
    questionNumber: '2.6.4.7',
    question: 'Does the employer punish workers for joining a union or engaging in union activities?',
    progress: 100,
    completed: 1,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Freedom of Association and Collective Bargaining',
    subsectionNumber: '2.6',
    category: 'Interference and Discrimination',
    categoryNumber: '2.6.4',
    questionNumber: '2.6.4.8',
    question: 'Does the employer threaten, intimidate, or harass workers who join a union or engage in union activities?',
    progress: 100,
    completed: 1,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Freedom of Association and Collective Bargaining',
    subsectionNumber: '2.6',
    category: 'Interference and Discrimination',
    categoryNumber: '2.6.4',
    questionNumber: '2.6.4.9',
    question: 'Has the employer terminated any worker or not renewed their contract due to the worker\'s union membership or union activities?',
    progress: 100,
    completed: 1,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Freedom of Association and Collective Bargaining',
    subsectionNumber: '2.6',
    category: 'Interference and Discrimination',
    categoryNumber: '2.6.4',
    questionNumber: '2.6.4.10',
    question: 'Has the employer terminated a union official without getting permission from the Ministry?',
    progress: 0,
    completed: 0,
    total: 1,
  },

  // 2.6.5 Collective Bargaining
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Freedom of Association and Collective Bargaining',
    subsectionNumber: '2.6',
    category: 'Collective Bargaining',
    categoryNumber: '2.6.5',
    questionNumber: '2.6.5.1',
    question: 'Does the employer consult with unions where legally required?',
    progress: 100,
    completed: 1,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Freedom of Association and Collective Bargaining',
    subsectionNumber: '2.6',
    category: 'Collective Bargaining',
    categoryNumber: '2.6.5',
    questionNumber: '2.6.5.2',
    question: 'Does the employer refuse to bargain collectively or refuse to bargain in good faith with the union, shop stewards or other worker representatives?',
    progress: 100,
    completed: 1,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Freedom of Association and Collective Bargaining',
    subsectionNumber: '2.6',
    category: 'Collective Bargaining',
    categoryNumber: '2.6.5',
    questionNumber: '2.6.5.3',
    question: 'If there is a collective bargaining agreement, are the provisions at least as favorable for workers as the law?',
    progress: 100,
    completed: 1,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Freedom of Association and Collective Bargaining',
    subsectionNumber: '2.6',
    category: 'Collective Bargaining',
    categoryNumber: '2.6.5',
    questionNumber: '2.6.5.4',
    question: 'Does the employer provide workers access to the collective bargaining agreements?',
    progress: 0,
    completed: 0,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Freedom of Association and Collective Bargaining',
    subsectionNumber: '2.6',
    category: 'Collective Bargaining',
    categoryNumber: '2.6.5',
    questionNumber: '2.6.5.5',
    question: 'Has the employer failed to implement any of the provisions of the collective bargaining agreement(s) in force?',
    progress: 100,
    completed: 1,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Freedom of Association and Collective Bargaining',
    subsectionNumber: '2.6',
    category: 'Collective Bargaining',
    categoryNumber: '2.6.5',
    questionNumber: '2.6.5.6',
    question: 'Has the employer tried to prevent any workers from participating in a strike?',
    progress: 100,
    completed: 1,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Freedom of Association and Collective Bargaining',
    subsectionNumber: '2.6',
    category: 'Collective Bargaining',
    categoryNumber: '2.6.5',
    questionNumber: '2.6.5.7',
    question: 'Has the employer hired new workers to replace striking workers during a strike?',
    progress: 100,
    completed: 1,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Freedom of Association and Collective Bargaining',
    subsectionNumber: '2.6',
    category: 'Collective Bargaining',
    categoryNumber: '2.6.5',
    questionNumber: '2.6.5.8',
    question: 'Has the employer punished any workers for participating in a strike?',
    progress: 100,
    completed: 1,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Freedom of Association and Collective Bargaining',
    subsectionNumber: '2.6',
    category: 'Collective Bargaining',
    categoryNumber: '2.6.5',
    questionNumber: '2.6.5.9',
    question: 'Were security guards, the police or armed forces called by the employer to break up a peaceful strike or assembly?',
    progress: 100,
    completed: 1,
    total: 1,
  },

  // 2.7 Compensation
  // 2.7.1 Minimum Wages/Piece Rate Wages
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Compensation',
    subsectionNumber: '2.7',
    category: 'Minimum Wages/Piece Rate Wages',
    categoryNumber: '2.7.1',
    questionNumber: '2.7.1.1',
    question: 'Does the employer pay at least minimum wage for ordinary hours of work to regular full-time workers?',
    progress: 0,
    completed: 0,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Compensation',
    subsectionNumber: '2.7',
    category: 'Minimum Wages/Piece Rate Wages',
    categoryNumber: '2.7.1',
    questionNumber: '2.7.1.2',
    question: 'Does the employer pay piece rate workers correctly for ordinary hours of work when their piece rate earnings fall below the minimum wage?',
    progress: 100,
    completed: 1,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Compensation',
    subsectionNumber: '2.7',
    category: 'Minimum Wages/Piece Rate Wages',
    categoryNumber: '2.7.1',
    questionNumber: '2.7.1.3',
    question: 'Does the employer pay at least minimum wage for all types of workers other than regular workers?',
    progress: 100,
    completed: 1,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Compensation',
    subsectionNumber: '2.7',
    category: 'Minimum Wages/Piece Rate Wages',
    categoryNumber: '2.7.1',
    questionNumber: '2.7.1.4',
    question: 'Is the piece rate set at a level that permits workers of average ability working normal hours to earn minimum wage?',
    progress: 100,
    completed: 1,
    total: 1,
  },

  // 2.7.2 Overtime Wages
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Compensation',
    subsectionNumber: '2.7',
    category: 'Overtime Wages',
    categoryNumber: '2.7.2',
    questionNumber: '2.7.2.1',
    question: 'Does the employer pay workers 150% of their normal wage for all ordinary overtime hours worked?',
    progress: 100,
    completed: 1,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Compensation',
    subsectionNumber: '2.7',
    category: 'Overtime Wages',
    categoryNumber: '2.7.2',
    questionNumber: '2.7.2.2',
    question: 'Does the employer pay workers double their normal wage for all overtime hours worked at night?',
    progress: 100,
    completed: 1,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Compensation',
    subsectionNumber: '2.7',
    category: 'Overtime Wages',
    categoryNumber: '2.7.2',
    questionNumber: '2.7.2.3',
    question: 'Does the employer pay workers double their normal wage for all hours worked on weekly rest days?',
    progress: 100,
    completed: 1,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Compensation',
    subsectionNumber: '2.7',
    category: 'Overtime Wages',
    categoryNumber: '2.7.2',
    questionNumber: '2.7.2.4',
    question: 'Does the employer pay all workers correctly for work on public holidays?',
    progress: 100,
    completed: 1,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Compensation',
    subsectionNumber: '2.7',
    category: 'Overtime Wages',
    categoryNumber: '2.7.2',
    questionNumber: '2.7.2.5',
    question: 'Does the employer pay all workers the correct meal allowance or give them a reasonable free meal when they work overtime?',
    progress: 100,
    completed: 1,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Compensation',
    subsectionNumber: '2.7',
    category: 'Overtime Wages',
    categoryNumber: '2.7.2',
    questionNumber: '2.7.2.6',
    question: 'Does the employer pay workers 130% of their normal wage for regular working hours worked at night?',
    progress: 100,
    completed: 1,
    total: 1,
  },

  // 2.7.3 Method of Payment
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Compensation',
    subsectionNumber: '2.7',
    category: 'Method of Payment',
    categoryNumber: '2.7.3',
    questionNumber: '2.7.3.1',
    question: 'Are workers paid on time, twice per month?',
    progress: 100,
    completed: 1,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Compensation',
    subsectionNumber: '2.7',
    category: 'Method of Payment',
    categoryNumber: '2.7.3',
    questionNumber: '2.7.3.2',
    question: 'Are workers\' full wages paid in the manner required (in cash, during working hours, at the workplace, and in legal tender)?',
    progress: 100,
    completed: 1,
    total: 1,
  },

  // 2.7.4 Wage Information, Use and Deduction
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Compensation',
    subsectionNumber: '2.7',
    category: 'Wage Information, Use and Deduction',
    categoryNumber: '2.7.4',
    questionNumber: '2.7.4.1',
    question: 'Has the employer made any unauthorized deductions from wages?',
    progress: 100,
    completed: 1,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Compensation',
    subsectionNumber: '2.7',
    category: 'Wage Information, Use and Deduction',
    categoryNumber: '2.7.4',
    questionNumber: '2.7.4.2',
    question: 'Does the employer keep only one accurate payroll record?',
    progress: 100,
    completed: 1,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Compensation',
    subsectionNumber: '2.7',
    category: 'Wage Information, Use and Deduction',
    categoryNumber: '2.7.4',
    questionNumber: '2.7.4.3',
    question: 'Does the employer properly inform workers about wage payments and deductions?',
    progress: 100,
    completed: 1,
    total: 1,
  },

  // 2.7.5 Paid Leave
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Compensation',
    subsectionNumber: '2.7',
    category: 'Paid Leave',
    categoryNumber: '2.7.5',
    questionNumber: '2.7.5.1',
    question: 'Does the employer pay workers correctly for paid public holidays?',
    progress: 100,
    completed: 1,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Compensation',
    subsectionNumber: '2.7',
    category: 'Paid Leave',
    categoryNumber: '2.7.5',
    questionNumber: '2.7.5.2',
    question: 'Does the employer pay workers correctly for annual leave?',
    progress: 100,
    completed: 1,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Compensation',
    subsectionNumber: '2.7',
    category: 'Paid Leave',
    categoryNumber: '2.7.5',
    questionNumber: '2.7.5.3',
    question: 'Does the employer provide paid sick leave as required by the factory\'s Internal Regulations, or if there are no Internal Regulations, as required by law?',
    progress: 100,
    completed: 1,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Compensation',
    subsectionNumber: '2.7',
    category: 'Paid Leave',
    categoryNumber: '2.7.5',
    questionNumber: '2.7.5.4',
    question: 'Does the employer pay workers correctly during special leave?',
    progress: 100,
    completed: 1,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Compensation',
    subsectionNumber: '2.7',
    category: 'Paid Leave',
    categoryNumber: '2.7.5',
    questionNumber: '2.7.5.5',
    question: 'Does the employer pay workers correctly for maternity leave?',
    progress: 100,
    completed: 1,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Compensation',
    subsectionNumber: '2.7',
    category: 'Paid Leave',
    categoryNumber: '2.7.5',
    questionNumber: '2.7.5.6',
    question: 'Does the employer pay workers correctly for the one hour of paid time off per day for breastfeeding?',
    progress: 100,
    completed: 1,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Compensation',
    subsectionNumber: '2.7',
    category: 'Paid Leave',
    categoryNumber: '2.7.5',
    questionNumber: '2.7.5.7',
    question: 'Does the employer pay workers correctly during work suspensions?',
    progress: 100,
    completed: 1,
    total: 1,
  },

  // 2.7.6 Social Security and Other Benefits
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Compensation',
    subsectionNumber: '2.7',
    category: 'Social Security and Other Benefits',
    categoryNumber: '2.7.6',
    questionNumber: '2.7.6.1',
    question: 'Does the employer pay the required employer contribution to the National Social Security Fund?',
    progress: 100,
    completed: 1,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Compensation',
    subsectionNumber: '2.7',
    category: 'Social Security and Other Benefits',
    categoryNumber: '2.7.6',
    questionNumber: '2.7.6.2',
    question: 'Does the employer pay workers their wages for the first day they miss work due to work-related accident?',
    progress: 100,
    completed: 1,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Compensation',
    subsectionNumber: '2.7',
    category: 'Social Security and Other Benefits',
    categoryNumber: '2.7.6',
    questionNumber: '2.7.6.3',
    question: 'Does the employer pay all workers who work regularly the correct attendance bonus during leave legally required by law?',
    progress: 100,
    completed: 1,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Compensation',
    subsectionNumber: '2.7',
    category: 'Social Security and Other Benefits',
    categoryNumber: '2.7.6',
    questionNumber: '2.7.6.4',
    question: 'Does the employer pay the correct attendance bonus to all new workers who start after the first of the month?',
    progress: 100,
    completed: 1,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Compensation',
    subsectionNumber: '2.7',
    category: 'Social Security and Other Benefits',
    categoryNumber: '2.7.6',
    questionNumber: '2.7.6.5',
    question: 'Does the employer pay all workers the correct mandatory wage supplements (including transportation allowance)?',
    progress: 100,
    completed: 1,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Compensation',
    subsectionNumber: '2.7',
    category: 'Social Security and Other Benefits',
    categoryNumber: '2.7.6',
    questionNumber: '2.7.6.6',
    question: 'Does the employer pay workers the correct seniority bonus?',
    progress: 100,
    completed: 1,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Compensation',
    subsectionNumber: '2.7',
    category: 'Social Security and Other Benefits',
    categoryNumber: '2.7.6',
    questionNumber: '2.7.6.7',
    question: 'Does the employer provide transport home or a place to sleep for workers who finish work between 22:00 and 05:00?',
    progress: 0,
    completed: 0,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Compensation',
    subsectionNumber: '2.7',
    category: 'Social Security and Other Benefits',
    categoryNumber: '2.7.6',
    questionNumber: '2.7.6.8',
    question: 'Does the employer pay UDC workers the correct seniority indemnity?',
    progress: 100,
    completed: 1,
    total: 1,
  },

  // 2.8 Contracts and Human Resources
  // 2.8.1 Fact-Gathering Questions
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Contracts and Human Resources',
    subsectionNumber: '2.8',
    category: 'Fact-Gathering Questions',
    categoryNumber: '2.8.1',
    questionNumber: '2.8.1.1',
    question: 'How many total workers are employed by the factory?',
    progress: 0,
    completed: 0,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Contracts and Human Resources',
    subsectionNumber: '2.8',
    category: 'Fact-Gathering Questions',
    categoryNumber: '2.8.1',
    questionNumber: '2.8.1.2',
    question: 'How many of the workers are men?',
    progress: 0,
    completed: 0,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Contracts and Human Resources',
    subsectionNumber: '2.8',
    category: 'Fact-Gathering Questions',
    categoryNumber: '2.8.1',
    questionNumber: '2.8.1.3',
    question: 'How many regular workers are employed by the factory?',
    progress: 0,
    completed: 0,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Contracts and Human Resources',
    subsectionNumber: '2.8',
    category: 'Fact-Gathering Questions',
    categoryNumber: '2.8.1',
    questionNumber: '2.8.1.4',
    question: 'How many probationary workers are employed by the factory?',
    progress: 0,
    completed: 0,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Contracts and Human Resources',
    subsectionNumber: '2.8',
    category: 'Fact-Gathering Questions',
    categoryNumber: '2.8.1',
    questionNumber: '2.8.1.5',
    question: 'How many casual workers are employed by the factory?',
    progress: 0,
    completed: 0,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Contracts and Human Resources',
    subsectionNumber: '2.8',
    category: 'Fact-Gathering Questions',
    categoryNumber: '2.8.1',
    questionNumber: '2.8.1.6',
    question: 'How many piece-rate workers are employed by the factory?',
    progress: 0,
    completed: 0,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Contracts and Human Resources',
    subsectionNumber: '2.8',
    category: 'Fact-Gathering Questions',
    categoryNumber: '2.8.1',
    questionNumber: '2.8.1.7',
    question: 'How many of the total workforce are migrant workers?',
    progress: 0,
    completed: 0,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Contracts and Human Resources',
    subsectionNumber: '2.8',
    category: 'Fact-Gathering Questions',
    categoryNumber: '2.8.1',
    questionNumber: '2.8.1.8',
    question: 'How many supervisors are employed by the factory?',
    progress: 0,
    completed: 0,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Contracts and Human Resources',
    subsectionNumber: '2.8',
    category: 'Fact-Gathering Questions',
    categoryNumber: '2.8.1',
    questionNumber: '2.8.1.9',
    question: 'Does the factory use subcontractors to complete all or part of the production process?',
    progress: 0,
    completed: 0,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Contracts and Human Resources',
    subsectionNumber: '2.8',
    category: 'Fact-Gathering Questions',
    categoryNumber: '2.8.1',
    questionNumber: '2.8.1.10',
    question: 'Does the factory use contractors to provide services at the factory that are not part of the production process?',
    progress: 0,
    completed: 0,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Contracts and Human Resources',
    subsectionNumber: '2.8',
    category: 'Fact-Gathering Questions',
    categoryNumber: '2.8.1',
    questionNumber: '2.8.1.11',
    question: 'How many workers with disabilities are employed by the factory?',
    progress: 0,
    completed: 0,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Contracts and Human Resources',
    subsectionNumber: '2.8',
    category: 'Fact-Gathering Questions',
    categoryNumber: '2.8.1',
    questionNumber: '2.8.1.12',
    question: 'Has the factory received any notices of noncompliance from the Labor Ministry since the last visit?',
    progress: 0,
    completed: 0,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Contracts and Human Resources',
    subsectionNumber: '2.8',
    category: 'Fact-Gathering Questions',
    categoryNumber: '2.8.1',
    questionNumber: '2.8.1.13',
    question: 'Does the factory have a valid business license?',
    progress: 0,
    completed: 0,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Contracts and Human Resources',
    subsectionNumber: '2.8',
    category: 'Fact-Gathering Questions',
    categoryNumber: '2.8.1',
    questionNumber: '2.8.1.14',
    question: 'Is there an adequate HR policy that is signed by top management with a clear commitment to meet all legal requirements?',
    progress: 0,
    completed: 0,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Contracts and Human Resources',
    subsectionNumber: '2.8',
    category: 'Fact-Gathering Questions',
    categoryNumber: '2.8.1',
    questionNumber: '2.8.1.15',
    question: 'Does the employer have an adequate recruitment procedure?',
    progress: 100,
    completed: 1,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Contracts and Human Resources',
    subsectionNumber: '2.8',
    category: 'Fact-Gathering Questions',
    categoryNumber: '2.8.1',
    questionNumber: '2.8.1.16',
    question: 'Does the employer have adequate disciplinary and termination procedures?',
    progress: 100,
    completed: 1,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Contracts and Human Resources',
    subsectionNumber: '2.8',
    category: 'Fact-Gathering Questions',
    categoryNumber: '2.8.1',
    questionNumber: '2.8.1.17',
    question: 'Does the employer have adequate grievance handling and dispute resolution procedures?',
    progress: 100,
    completed: 1,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Contracts and Human Resources',
    subsectionNumber: '2.8',
    category: 'Fact-Gathering Questions',
    categoryNumber: '2.8.1',
    questionNumber: '2.8.1.18',
    question: 'Does the employer adequately assign accountability to management for following factory policies and procedures?',
    progress: 0,
    completed: 0,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Contracts and Human Resources',
    subsectionNumber: '2.8',
    category: 'Fact-Gathering Questions',
    categoryNumber: '2.8.1',
    questionNumber: '2.8.1.19',
    question: 'Does the employer adequately communicate and implement HR policies and procedures?',
    progress: 100,
    completed: 1,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Contracts and Human Resources',
    subsectionNumber: '2.8',
    category: 'Fact-Gathering Questions',
    categoryNumber: '2.8.1',
    questionNumber: '2.8.1.20',
    question: 'Does the employer adequately investigate performance under HR policies and procedures to identify weaknesses?',
    progress: 0,
    completed: 0,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Contracts and Human Resources',
    subsectionNumber: '2.8',
    category: 'Fact-Gathering Questions',
    categoryNumber: '2.8.1',
    questionNumber: '2.8.1.21',
    question: 'Did workers freely choose their representatives on the bipartite committee, and do workers know who their representatives are?',
    progress: 0,
    completed: 0,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Contracts and Human Resources',
    subsectionNumber: '2.8',
    category: 'Fact-Gathering Questions',
    categoryNumber: '2.8.1',
    questionNumber: '2.8.1.22',
    question: 'Has there been any retaliation against worker representatives due to their activity on the bipartite committee?',
    progress: 100,
    completed: 1,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Contracts and Human Resources',
    subsectionNumber: '2.8',
    category: 'Fact-Gathering Questions',
    categoryNumber: '2.8.1',
    questionNumber: '2.8.1.23',
    question: 'Where there is a union in the factory, does management maintain open communication channels with trade union representatives?',
    progress: 100,
    completed: 1,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Contracts and Human Resources',
    subsectionNumber: '2.8',
    category: 'Fact-Gathering Questions',
    categoryNumber: '2.8.1',
    questionNumber: '2.8.1.24',
    question: 'Is the bipartite committee used as an alternative to a trade union?',
    progress: 100,
    completed: 1,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Contracts and Human Resources',
    subsectionNumber: '2.8',
    category: 'Fact-Gathering Questions',
    categoryNumber: '2.8.1',
    questionNumber: '2.8.1.25',
    question: 'Was the grievance mechanism developed through social dialogue between workers/unions and managers?',
    progress: 0,
    completed: 0,
    total: 1,
  },

  // 2.8.2 Employment Contracts
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Contracts and Human Resources',
    subsectionNumber: '2.8',
    category: 'Employment Contracts',
    categoryNumber: '2.8.2',
    questionNumber: '2.8.2.1',
    question: 'Do the employment contracts specify the terms and conditions of employment?',
    progress: 100,
    completed: 1,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Contracts and Human Resources',
    subsectionNumber: '2.8',
    category: 'Employment Contracts',
    categoryNumber: '2.8.2',
    questionNumber: '2.8.2.2',
    question: 'Do the employment contracts comply with Cambodian labour law and with the factory\'s internal regulations?',
    progress: 100,
    completed: 1,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Contracts and Human Resources',
    subsectionNumber: '2.8',
    category: 'Employment Contracts',
    categoryNumber: '2.8.2',
    questionNumber: '2.8.2.3',
    question: 'Does management have a system to ensure that workers understand the terms and conditions of employment?',
    progress: 100,
    completed: 1,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Contracts and Human Resources',
    subsectionNumber: '2.8',
    category: 'Employment Contracts',
    categoryNumber: '2.8.2',
    questionNumber: '2.8.2.4',
    question: 'Do all persons who perform work for the factory, both on the premises and offsite, have a contract?',
    progress: 100,
    completed: 1,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Contracts and Human Resources',
    subsectionNumber: '2.8',
    category: 'Employment Contracts',
    categoryNumber: '2.8.2',
    questionNumber: '2.8.2.5',
    question: 'Do the internal regulations comply with legal requirements?',
    progress: 100,
    completed: 1,
    total: 1,
  },

  // 2.8.3 Contracting Procedures
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Contracts and Human Resources',
    subsectionNumber: '2.8',
    category: 'Contracting Procedures',
    categoryNumber: '2.8.3',
    questionNumber: '2.8.3.1',
    question: 'Do workers have to pay anyone to get a job?',
    progress: 100,
    completed: 1,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Contracts and Human Resources',
    subsectionNumber: '2.8',
    category: 'Contracting Procedures',
    categoryNumber: '2.8.3',
    questionNumber: '2.8.3.2',
    question: 'Does the employer comply with limits on the period of employment for apprentices and probationary workers?',
    progress: 100,
    completed: 1,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Contracts and Human Resources',
    subsectionNumber: '2.8',
    category: 'Contracting Procedures',
    categoryNumber: '2.8.3',
    questionNumber: '2.8.3.3',
    question: 'Does the employer include the entire period of continuous employment when determining workers\' entitlements?',
    progress: 100,
    completed: 1,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Contracts and Human Resources',
    subsectionNumber: '2.8',
    category: 'Contracting Procedures',
    categoryNumber: '2.8.3',
    questionNumber: '2.8.3.4',
    question: 'Does the employer comply with the legal limit on the use of fixed term contracts?',
    progress: 100,
    completed: 1,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Contracts and Human Resources',
    subsectionNumber: '2.8',
    category: 'Contracting Procedures',
    categoryNumber: '2.8.3',
    questionNumber: '2.8.3.5',
    question: 'Have you found non-compliance with legal requirements for compensation, contracts, OSH and/or working time that apply specifically to migrant workers?',
    progress: 0,
    completed: 0,
    total: 1,
  },

  // 2.8.4 Termination
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Contracts and Human Resources',
    subsectionNumber: '2.8',
    category: 'Termination',
    categoryNumber: '2.8.4',
    questionNumber: '2.8.4.1',
    question: 'Does the employer pay all outstanding wages and indemnities within 48 hours of termination?',
    progress: 0,
    completed: 0,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Contracts and Human Resources',
    subsectionNumber: '2.8',
    category: 'Termination',
    categoryNumber: '2.8.4',
    questionNumber: '2.8.4.2',
    question: 'Does the employer only terminate workers for valid reasons?',
    progress: 0,
    completed: 0,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Contracts and Human Resources',
    subsectionNumber: '2.8',
    category: 'Termination',
    categoryNumber: '2.8.4',
    questionNumber: '2.8.4.3',
    question: 'Does the employer provide workers proper notice, and an opportunity to defend themselves before they are terminated?',
    progress: 0,
    completed: 0,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Contracts and Human Resources',
    subsectionNumber: '2.8',
    category: 'Termination',
    categoryNumber: '2.8.4',
    questionNumber: '2.8.4.4',
    question: 'Does the employer pay workers the correct severance pay?',
    progress: 0,
    completed: 0,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Contracts and Human Resources',
    subsectionNumber: '2.8',
    category: 'Termination',
    categoryNumber: '2.8.4',
    questionNumber: '2.8.4.5',
    question: 'Does the employer pay workers their outstanding wages and the correct seniority indemnity for dismissal?',
    progress: 0,
    completed: 0,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Contracts and Human Resources',
    subsectionNumber: '2.8',
    category: 'Termination',
    categoryNumber: '2.8.4',
    questionNumber: '2.8.4.6',
    question: 'Does the employer compensate workers for unused paid annual leave when they resign or are terminated?',
    progress: 0,
    completed: 0,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Contracts and Human Resources',
    subsectionNumber: '2.8',
    category: 'Termination',
    categoryNumber: '2.8.4',
    questionNumber: '2.8.4.7',
    question: 'Does the employer pay terminated workers the correct damages when required?',
    progress: 0,
    completed: 0,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Contracts and Human Resources',
    subsectionNumber: '2.8',
    category: 'Termination',
    categoryNumber: '2.8.4',
    questionNumber: '2.8.4.8',
    question: 'Does the employer comply with legal requirements before suspending workers or reducing the size of the workforce?',
    progress: 0,
    completed: 0,
    total: 1,
  },

  // 2.8.5 Dialogue, Discipline and Disputes — collapsed in source
  // TODO: expand to add individual questions

  // 2.9 Occupational Safety and Health
  // 2.9.1 Fact-Gathering Questions
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Occupational Safety and Health',
    subsectionNumber: '2.9',
    category: 'Fact-Gathering Questions',
    categoryNumber: '2.9.1',
    questionNumber: '2.9.1.1',
    question: 'Is there an adequate emergency preparedness procedure?',
    progress: 0,
    completed: 0,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Occupational Safety and Health',
    subsectionNumber: '2.9',
    category: 'Fact-Gathering Questions',
    categoryNumber: '2.9.1',
    questionNumber: '2.9.1.2',
    question: 'Is there an adequate hazard/risk management and control procedure?',
    progress: 0,
    completed: 0,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Occupational Safety and Health',
    subsectionNumber: '2.9',
    category: 'Fact-Gathering Questions',
    categoryNumber: '2.9.1',
    questionNumber: '2.9.1.3',
    question: 'Is there an adequate accident investigation procedure?',
    progress: 0,
    completed: 0,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Occupational Safety and Health',
    subsectionNumber: '2.9',
    category: 'Fact-Gathering Questions',
    categoryNumber: '2.9.1',
    questionNumber: '2.9.1.4',
    question: 'Does the employer adequately assign accountability to management for carrying out health and safety responsibilities?',
    progress: 0,
    completed: 0,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Occupational Safety and Health',
    subsectionNumber: '2.9',
    category: 'Fact-Gathering Questions',
    categoryNumber: '2.9.1',
    questionNumber: '2.9.1.5',
    question: 'Does the employer adequately communicate and implement OSH policies and procedures?',
    progress: 0,
    completed: 0,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Occupational Safety and Health',
    subsectionNumber: '2.9',
    category: 'Fact-Gathering Questions',
    categoryNumber: '2.9.1',
    questionNumber: '2.9.1.6',
    question: 'Does the employer adequately investigate, monitor and measure OSH issues to identify root causes and make necessary improvements?',
    progress: 0,
    completed: 0,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Occupational Safety and Health',
    subsectionNumber: '2.9',
    category: 'Fact-Gathering Questions',
    categoryNumber: '2.9.1',
    questionNumber: '2.9.1.7',
    question: 'How many work related accidents have been reported to Social Security?',
    progress: 0,
    completed: 0,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Occupational Safety and Health',
    subsectionNumber: '2.9',
    category: 'Fact-Gathering Questions',
    categoryNumber: '2.9.1',
    questionNumber: '2.9.1.8',
    question: 'Are there any other issues of concern not addressed elsewhere in the report related to workers\'/supervisors\' accommodation?',
    progress: 0,
    completed: 0,
    total: 1,
  },

  // 2.9.2 OSH Management Systems
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Occupational Safety and Health',
    subsectionNumber: '2.9',
    category: 'OSH Management Systems',
    categoryNumber: '2.9.2',
    questionNumber: '2.9.2.1',
    question: 'Is there an adequate OSH Policy that is signed by top management?',
    progress: 100,
    completed: 1,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Occupational Safety and Health',
    subsectionNumber: '2.9',
    category: 'OSH Management Systems',
    categoryNumber: '2.9.2',
    questionNumber: '2.9.2.2',
    question: 'Has the employer developed mechanisms to ensure cooperation between workers and management on OSH matters?',
    progress: 0,
    completed: 0,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Occupational Safety and Health',
    subsectionNumber: '2.9',
    category: 'OSH Management Systems',
    categoryNumber: '2.9.2',
    questionNumber: '2.9.2.3',
    question: 'Does the employer record work-related accidents and illnesses and report them to the Ministry?',
    progress: 0,
    completed: 0,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Occupational Safety and Health',
    subsectionNumber: '2.9',
    category: 'OSH Management Systems',
    categoryNumber: '2.9.2',
    questionNumber: '2.9.2.4',
    question: 'Does the employer have legally required construction/building permits?',
    progress: 0,
    completed: 0,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Occupational Safety and Health',
    subsectionNumber: '2.9',
    category: 'OSH Management Systems',
    categoryNumber: '2.9.2',
    questionNumber: '2.9.2.5',
    question: 'Does the employer conduct regular hazards and risk assessment?',
    progress: 0,
    completed: 0,
    total: 1,
  },

  // 2.9.3 Chemicals and Hazardous Substances
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Occupational Safety and Health',
    subsectionNumber: '2.9',
    category: 'Chemicals and Hazardous Substances',
    categoryNumber: '2.9.3',
    questionNumber: '2.9.3.1',
    question: 'Does the employer keep an inventory of chemicals and hazardous substances used in the workplace?',
    progress: 100,
    completed: 1,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Occupational Safety and Health',
    subsectionNumber: '2.9',
    category: 'Chemicals and Hazardous Substances',
    categoryNumber: '2.9.3',
    questionNumber: '2.9.3.2',
    question: 'Are chemicals and hazardous substances properly labelled?',
    progress: 100,
    completed: 1,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Occupational Safety and Health',
    subsectionNumber: '2.9',
    category: 'Chemicals and Hazardous Substances',
    categoryNumber: '2.9.3',
    questionNumber: '2.9.3.3',
    question: 'Are chemicals and hazardous substances properly stored?',
    progress: 100,
    completed: 1,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Occupational Safety and Health',
    subsectionNumber: '2.9',
    category: 'Chemicals and Hazardous Substances',
    categoryNumber: '2.9.3',
    questionNumber: '2.9.3.4',
    question: 'Does the employer have chemical safety data sheets for the hazardous chemicals used in the workplace?',
    progress: 100,
    completed: 1,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Occupational Safety and Health',
    subsectionNumber: '2.9',
    category: 'Chemicals and Hazardous Substances',
    categoryNumber: '2.9.3',
    questionNumber: '2.9.3.5',
    question: 'Has the employer taken action to prevent and limit workers\' exposure to chemicals and hazardous substances?',
    progress: 100,
    completed: 1,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Occupational Safety and Health',
    subsectionNumber: '2.9',
    category: 'Chemicals and Hazardous Substances',
    categoryNumber: '2.9.3',
    questionNumber: '2.9.3.6',
    question: 'Has the employer effectively trained workers who work with chemicals and hazardous substances?',
    progress: 100,
    completed: 1,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Occupational Safety and Health',
    subsectionNumber: '2.9',
    category: 'Chemicals and Hazardous Substances',
    categoryNumber: '2.9.3',
    questionNumber: '2.9.3.7',
    question: 'Does the employer provide adequate washing facilities and cleansing materials in the event of exposure to hazardous substances?',
    progress: 100,
    completed: 1,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Occupational Safety and Health',
    subsectionNumber: '2.9',
    category: 'Chemicals and Hazardous Substances',
    categoryNumber: '2.9.3',
    questionNumber: '2.9.3.8',
    question: 'Has the employer prepared for response, control and cleaning of chemical spills?',
    progress: 100,
    completed: 1,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Occupational Safety and Health',
    subsectionNumber: '2.9',
    category: 'Chemicals and Hazardous Substances',
    categoryNumber: '2.9.3',
    questionNumber: '2.9.3.9',
    question: 'Are chemical mixing rooms properly equipped and used?',
    progress: 100,
    completed: 1,
    total: 1,
  },

  // 2.9.4 Worker Protection
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Occupational Safety and Health',
    subsectionNumber: '2.9',
    category: 'Worker Protection',
    categoryNumber: '2.9.4',
    questionNumber: '2.9.4.1',
    question: 'Are workers punished if they remove themselves from work situations that they believe present an imminent danger?',
    progress: 100,
    completed: 1,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Occupational Safety and Health',
    subsectionNumber: '2.9',
    category: 'Worker Protection',
    categoryNumber: '2.9.4',
    questionNumber: '2.9.4.2',
    question: 'Has the employer provided workers with dust masks when necessary?',
    progress: 100,
    completed: 1,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Occupational Safety and Health',
    subsectionNumber: '2.9',
    category: 'Worker Protection',
    categoryNumber: '2.9.4',
    questionNumber: '2.9.4.3',
    question: 'Has the employer provided workers who work with chemical substances with proper clothing and personal protective equipment?',
    progress: 100,
    completed: 1,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Occupational Safety and Health',
    subsectionNumber: '2.9',
    category: 'Worker Protection',
    categoryNumber: '2.9.4',
    questionNumber: '2.9.4.4',
    question: 'Has the employer provided workers with metal gloves when necessary?',
    progress: 100,
    completed: 1,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Occupational Safety and Health',
    subsectionNumber: '2.9',
    category: 'Worker Protection',
    categoryNumber: '2.9.4',
    questionNumber: '2.9.4.5',
    question: 'Has the employer provided workers with ear plugs when necessary?',
    progress: 100,
    completed: 1,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Occupational Safety and Health',
    subsectionNumber: '2.9',
    category: 'Worker Protection',
    categoryNumber: '2.9.4',
    questionNumber: '2.9.4.6',
    question: 'Has the employer provided workers with necessary PPE to protect against wet processes when necessary?',
    progress: 100,
    completed: 1,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Occupational Safety and Health',
    subsectionNumber: '2.9',
    category: 'Worker Protection',
    categoryNumber: '2.9.4',
    questionNumber: '2.9.4.7',
    question: 'Has the employer provided workers with other PPE when necessary?',
    progress: 100,
    completed: 1,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Occupational Safety and Health',
    subsectionNumber: '2.9',
    category: 'Worker Protection',
    categoryNumber: '2.9.4',
    questionNumber: '2.9.4.8',
    question: 'Are workers effectively trained and encouraged to properly use personal protective equipment and machines?',
    progress: 100,
    completed: 1,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Occupational Safety and Health',
    subsectionNumber: '2.9',
    category: 'Worker Protection',
    categoryNumber: '2.9.4',
    questionNumber: '2.9.4.9',
    question: 'Does the employer comply with ergonomic requirements?',
    progress: 100,
    completed: 1,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Occupational Safety and Health',
    subsectionNumber: '2.9',
    category: 'Worker Protection',
    categoryNumber: '2.9.4',
    questionNumber: '2.9.4.10',
    question: 'Are guards properly installed and maintained on all dangerous machines and equipment?',
    progress: 100,
    completed: 1,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Occupational Safety and Health',
    subsectionNumber: '2.9',
    category: 'Worker Protection',
    categoryNumber: '2.9.4',
    questionNumber: '2.9.4.11',
    question: 'Are electrical wires, cables, switches, plugs and equipment (e.g. transformer, generator, electrical panel, circuit breaker) properly installed and maintained?',
    progress: 0,
    completed: 0,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Occupational Safety and Health',
    subsectionNumber: '2.9',
    category: 'Worker Protection',
    categoryNumber: '2.9.4',
    questionNumber: '2.9.4.12',
    question: 'Do the operators/technicians for boiler, generator, compressor, and pressure vessels have legally required permit and training?',
    progress: 0,
    completed: 0,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Occupational Safety and Health',
    subsectionNumber: '2.9',
    category: 'Worker Protection',
    categoryNumber: '2.9.4',
    questionNumber: '2.9.4.13',
    question: 'Does the employer have the legally required permits for the installation and operation of boiler, generator, compressor, and pressure vessels?',
    progress: 0,
    completed: 0,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Occupational Safety and Health',
    subsectionNumber: '2.9',
    category: 'Worker Protection',
    categoryNumber: '2.9.4',
    questionNumber: '2.9.4.14',
    question: 'Are appropriate safety warnings posted in the workplace?',
    progress: 0,
    completed: 0,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Occupational Safety and Health',
    subsectionNumber: '2.9',
    category: 'Worker Protection',
    categoryNumber: '2.9.4',
    questionNumber: '2.9.4.15',
    question: 'Has the employer taken legally required measures to protect workers from falls from heights?',
    progress: 0,
    completed: 0,
    total: 1,
  },

  // 2.9.5 Working Environment
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Occupational Safety and Health',
    subsectionNumber: '2.9',
    category: 'Working Environment',
    categoryNumber: '2.9.5',
    questionNumber: '2.9.5.1',
    question: 'Are the temperature and ventilation acceptable?',
    progress: 0,
    completed: 0,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Occupational Safety and Health',
    subsectionNumber: '2.9',
    category: 'Working Environment',
    categoryNumber: '2.9.5',
    questionNumber: '2.9.5.2',
    question: 'Are noise levels acceptable?',
    progress: 0,
    completed: 0,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Occupational Safety and Health',
    subsectionNumber: '2.9',
    category: 'Working Environment',
    categoryNumber: '2.9.5',
    questionNumber: '2.9.5.3',
    question: 'Is the workplace adequately lit?',
    progress: 0,
    completed: 0,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Occupational Safety and Health',
    subsectionNumber: '2.9',
    category: 'Working Environment',
    categoryNumber: '2.9.5',
    questionNumber: '2.9.5.4',
    question: 'Is the workplace clean and tidy?',
    progress: 0,
    completed: 0,
    total: 1,
  },

  // 2.9.6 Welfare Facilities
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Occupational Safety and Health',
    subsectionNumber: '2.9',
    category: 'Welfare Facilities',
    categoryNumber: '2.9.6',
    questionNumber: '2.9.6.1',
    question: 'Does the workplace have adequate accessible toilets?',
    progress: 0,
    completed: 0,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Occupational Safety and Health',
    subsectionNumber: '2.9',
    category: 'Welfare Facilities',
    categoryNumber: '2.9.6',
    questionNumber: '2.9.6.2',
    question: 'Does the workplace have adequate hand washing facilities and adequate soap?',
    progress: 0,
    completed: 0,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Occupational Safety and Health',
    subsectionNumber: '2.9',
    category: 'Welfare Facilities',
    categoryNumber: '2.9.6',
    questionNumber: '2.9.6.3',
    question: 'Does the employer provide workers enough free safe drinking water?',
    progress: 100,
    completed: 1,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Occupational Safety and Health',
    subsectionNumber: '2.9',
    category: 'Welfare Facilities',
    categoryNumber: '2.9.6',
    questionNumber: '2.9.6.4',
    question: 'Does employer provide cups or other sanitary means for drinking water?',
    progress: 0,
    completed: 0,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Occupational Safety and Health',
    subsectionNumber: '2.9',
    category: 'Welfare Facilities',
    categoryNumber: '2.9.6',
    questionNumber: '2.9.6.5',
    question: 'Does the workplace have a functioning and accessible nursing room?',
    progress: 0,
    completed: 0,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Occupational Safety and Health',
    subsectionNumber: '2.9',
    category: 'Welfare Facilities',
    categoryNumber: '2.9.6',
    questionNumber: '2.9.6.6',
    question: 'Does the workplace have a functioning day care centre or pay childcare costs of women employees?',
    progress: 0,
    completed: 0,
    total: 1,
  },

  // 2.9.7 Health Services and First Aid
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Occupational Safety and Health',
    subsectionNumber: '2.9',
    category: 'Health Services and First Aid',
    categoryNumber: '2.9.7',
    questionNumber: '2.9.7.1',
    question: 'Do workers undergo a medical examination before being employed?',
    progress: 0,
    completed: 0,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Occupational Safety and Health',
    subsectionNumber: '2.9',
    category: 'Health Services and First Aid',
    categoryNumber: '2.9.7',
    questionNumber: '2.9.7.2',
    question: 'Does the employer address safety and health risks to pregnant workers or workers who are nursing?',
    progress: 0,
    completed: 0,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Occupational Safety and Health',
    subsectionNumber: '2.9',
    category: 'Health Services and First Aid',
    categoryNumber: '2.9.7',
    questionNumber: '2.9.7.3',
    question: 'Does the workplace have a functioning HIV/AIDS Committee?',
    progress: 0,
    completed: 0,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Occupational Safety and Health',
    subsectionNumber: '2.9',
    category: 'Health Services and First Aid',
    categoryNumber: '2.9.7',
    questionNumber: '2.9.7.4',
    question: 'Does the workplace have an adequately equipped and staffed infirmary?',
    progress: 0,
    completed: 0,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Occupational Safety and Health',
    subsectionNumber: '2.9',
    category: 'Health Services and First Aid',
    categoryNumber: '2.9.7',
    questionNumber: '2.9.7.5',
    question: 'Has the employer ensured that there is a sufficient number of readily accessible first aid boxes/supplies in the workplace?',
    progress: 0,
    completed: 0,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Occupational Safety and Health',
    subsectionNumber: '2.9',
    category: 'Health Services and First Aid',
    categoryNumber: '2.9.7',
    questionNumber: '2.9.7.6',
    question: 'Has the employer provided first-aid training for workers?',
    progress: 0,
    completed: 0,
    total: 1,
  },
];

async function seed() {
  try {
    await mongoose.connect(process.env.MONGODB_URI);
    console.log('Connected to MongoDB');

    await ChecklistItem.deleteMany({ section: 'ILO' });
    console.log('Cleared existing ILO checklist items');

    const result = await ChecklistItem.insertMany(iloQuestions);
    console.log(`Inserted ${result.length} checklist items`);

    await mongoose.disconnect();
    console.log('Done!');
  } catch (err) {
    console.error('Seed error:', err);
    process.exit(1);
  }
}

seed();
