const mongoose = require('mongoose');
require('dotenv').config();
const ChecklistItem = require('../models/ChecklistItem');

const iloQuestions = [
  // 2.1 Key Strengths and Process Integrity
  // 2.1.1 Fact-Gathering Questions
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Key Strengths and Process Integrity',
    subsectionNumber: '2.1',
    category: 'Fact-Gathering Questions',
    categoryNumber: '2.1.1',
    questionNumber: '2.1.1.1',
    question: 'Is there any good practice/progress made or key strength in the factory?',
    progress: 100,
    completed: 1,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Key Strengths and Process Integrity',
    subsectionNumber: '2.1',
    category: 'Fact-Gathering Questions',
    categoryNumber: '2.1.1',
    questionNumber: '2.1.1.2',
    question: 'Was the assessor\'s access to the enterprise unreasonably restricted?',
    progress: 0,
    completed: 0,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Key Strengths and Process Integrity',
    subsectionNumber: '2.1',
    category: 'Fact-Gathering Questions',
    categoryNumber: '2.1.1',
    questionNumber: '2.1.1.3',
    question: 'Were documents provided in a timely manner?',
    progress: 0,
    completed: 0,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Key Strengths and Process Integrity',
    subsectionNumber: '2.1',
    category: 'Fact-Gathering Questions',
    categoryNumber: '2.1.1',
    questionNumber: '2.1.1.4',
    question: 'Number of assessment visits prior to STAR Cycle 1:',
    progress: 0,
    completed: 0,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Key Strengths and Process Integrity',
    subsectionNumber: '2.1',
    category: 'Fact-Gathering Questions',
    categoryNumber: '2.1.1',
    questionNumber: '2.1.1.5',
    question: 'How many person days were spent on the assessment visit?',
    progress: 0,
    completed: 0,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Key Strengths and Process Integrity',
    subsectionNumber: '2.1',
    category: 'Fact-Gathering Questions',
    categoryNumber: '2.1.1',
    questionNumber: '2.1.1.6',
    question: 'Provide the titles of the management staff interviewed.',
    progress: 0,
    completed: 0,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Key Strengths and Process Integrity',
    subsectionNumber: '2.1',
    category: 'Fact-Gathering Questions',
    categoryNumber: '2.1.1',
    questionNumber: '2.1.1.7',
    question: 'Briefly describe the interviews with workers/ union leaders/ shop stewards:',
    progress: 0,
    completed: 0,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Key Strengths and Process Integrity',
    subsectionNumber: '2.1',
    category: 'Fact-Gathering Questions',
    categoryNumber: '2.1.1',
    questionNumber: '2.1.1.8',
    question: 'Describe any significant concerns about process integrity.',
    progress: 0,
    completed: 0,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Key Strengths and Process Integrity',
    subsectionNumber: '2.1',
    category: 'Fact-Gathering Questions',
    categoryNumber: '2.1.1',
    questionNumber: '2.1.1.9',
    question: 'Are there any issues of concern not addressed elsewhere in the report?',
    progress: 0,
    completed: 0,
    total: 1,
  },

  // 2.2 Learning
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Learning',
    subsectionNumber: '2.2',
    category: 'Learning',
    categoryNumber: '2.2.1',
    questionNumber: '2.2.1',
    question: 'Has management consulted with elected worker representatives, including trade unions (if present) in determining the need for and scope of the assessment?',
    progress: 100,
    completed: 1,
    total: 1,
  },

  // 2.3 Child Labour
  // 2.3.1 Child Labourers
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Child Labour',
    subsectionNumber: '2.3',
    category: 'Child Labourers',
    categoryNumber: '2.3.1',
    questionNumber: '2.3.1.1',
    question: 'Have you found any workers under the age of 15?',
    progress: 100,
    completed: 1,
    total: 1,
  },

  // 2.3.2 Hazardous Work and other Worst Forms
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Child Labour',
    subsectionNumber: '2.3',
    category: 'Hazardous Work and other Worst Forms',
    categoryNumber: '2.3.2',
    questionNumber: '2.3.2.1',
    question: 'Do workers who are under age 18 perform work that is hazardous by nature?',
    progress: 100,
    completed: 1,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Child Labour',
    subsectionNumber: '2.3',
    category: 'Hazardous Work and other Worst Forms',
    categoryNumber: '2.3.2',
    questionNumber: '2.3.2.2',
    question: 'Are any workers who are under age 18 working at night, or working more than 8 hours per day (including overtime)?',
    progress: 100,
    completed: 1,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Child Labour',
    subsectionNumber: '2.3',
    category: 'Hazardous Work and other Worst Forms',
    categoryNumber: '2.3.2',
    questionNumber: '2.3.2.3',
    question: 'Does the employer subject any workers under age 18 to the unconditional worst forms of child labour?',
    progress: 100,
    completed: 1,
    total: 1,
  },

  // 2.3.3 Documentation and Protection of Young Workers
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Child Labour',
    subsectionNumber: '2.3',
    category: 'Documentation and Protection of Young Workers',
    categoryNumber: '2.3.3',
    questionNumber: '2.3.3.1',
    question: 'Does the employer reliably verify the age of workers prior to hiring?',
    progress: 100,
    completed: 1,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Child Labour',
    subsectionNumber: '2.3',
    category: 'Documentation and Protection of Young Workers',
    categoryNumber: '2.3.3',
    questionNumber: '2.3.3.2',
    question: 'Does the employer keep a register and get consent from the guardians of workers under 18 years of age?',
    progress: 100,
    completed: 1,
    total: 1,
  },

  // 2.4 Discrimination
  // 2.4.1 Race and Origin
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Discrimination',
    subsectionNumber: '2.4',
    category: 'Race and Origin',
    categoryNumber: '2.4.1',
    questionNumber: '2.4.1.1',
    question: 'Do recruitment materials such as job announcements or job application forms refer to the applicant\'s race, colour or origin?',
    progress: 100,
    completed: 1,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Discrimination',
    subsectionNumber: '2.4',
    category: 'Race and Origin',
    categoryNumber: '2.4.1',
    questionNumber: '2.4.1.2',
    question: 'Is an applicant\'s race, colour or origin a factor in hiring decisions?',
    progress: 100,
    completed: 1,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Discrimination',
    subsectionNumber: '2.4',
    category: 'Race and Origin',
    categoryNumber: '2.4.1',
    questionNumber: '2.4.1.3',
    question: 'Is race, colour or origin a factor in decisions regarding conditions of work?',
    progress: 100,
    completed: 1,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Discrimination',
    subsectionNumber: '2.4',
    category: 'Race and Origin',
    categoryNumber: '2.4.1',
    questionNumber: '2.4.1.4',
    question: 'Is race, colour or origin a factor in decisions regarding pay?',
    progress: 100,
    completed: 1,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Discrimination',
    subsectionNumber: '2.4',
    category: 'Race and Origin',
    categoryNumber: '2.4.1',
    questionNumber: '2.4.1.5',
    question: 'Is race, colour or origin a factor in decisions regarding opportunities for promotion or access to training?',
    progress: 100,
    completed: 1,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Discrimination',
    subsectionNumber: '2.4',
    category: 'Race and Origin',
    categoryNumber: '2.4.1',
    questionNumber: '2.4.1.6',
    question: 'Is there harassment of workers on the basis of race, colour or origin?',
    progress: 100,
    completed: 1,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Discrimination',
    subsectionNumber: '2.4',
    category: 'Race and Origin',
    categoryNumber: '2.4.1',
    questionNumber: '2.4.1.7',
    question: 'Is race, colour or origin a factor in the employer\'s decisions regarding termination or retirement of workers?',
    progress: 100,
    completed: 1,
    total: 1,
  },

  // 2.4.2 Religion and Political Opinion
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Discrimination',
    subsectionNumber: '2.4',
    category: 'Religion and Political Opinion',
    categoryNumber: '2.4.2',
    questionNumber: '2.4.2.1',
    question: 'Do recruitment materials such as job announcements or job application forms refer to the applicant\'s religion or political opinion?',
    progress: 100,
    completed: 1,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Discrimination',
    subsectionNumber: '2.4',
    category: 'Religion and Political Opinion',
    categoryNumber: '2.4.2',
    questionNumber: '2.4.2.2',
    question: 'Is an applicant\'s religion or political opinion a factor in hiring decisions?',
    progress: 100,
    completed: 1,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Discrimination',
    subsectionNumber: '2.4',
    category: 'Religion and Political Opinion',
    categoryNumber: '2.4.2',
    questionNumber: '2.4.2.3',
    question: 'Is religion or political opinion a factor in decisions regarding conditions of work?',
    progress: 100,
    completed: 1,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Discrimination',
    subsectionNumber: '2.4',
    category: 'Religion and Political Opinion',
    categoryNumber: '2.4.2',
    questionNumber: '2.4.2.4',
    question: 'Is religion or political opinion a factor in decisions regarding pay?',
    progress: 100,
    completed: 1,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Discrimination',
    subsectionNumber: '2.4',
    category: 'Religion and Political Opinion',
    categoryNumber: '2.4.2',
    questionNumber: '2.4.2.5',
    question: 'Is religion or political opinion a factor in decisions regarding opportunities for promotion or access to training?',
    progress: 100,
    completed: 1,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Discrimination',
    subsectionNumber: '2.4',
    category: 'Religion and Political Opinion',
    categoryNumber: '2.4.2',
    questionNumber: '2.4.2.6',
    question: 'Is there harassment of workers on the basis of religion or political opinion?',
    progress: 100,
    completed: 1,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Discrimination',
    subsectionNumber: '2.4',
    category: 'Religion and Political Opinion',
    categoryNumber: '2.4.2',
    questionNumber: '2.4.2.7',
    question: 'Is religion or political opinion a factor in the employer\'s decisions regarding termination or retirement of workers?',
    progress: 100,
    completed: 1,
    total: 1,
  },

  // 2.4.3 Gender
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Discrimination',
    subsectionNumber: '2.4',
    category: 'Gender',
    categoryNumber: '2.4.3',
    questionNumber: '2.4.3.1',
    question: 'Do job announcements refer to the applicant\'s gender?',
    progress: 100,
    completed: 1,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Discrimination',
    subsectionNumber: '2.4',
    category: 'Gender',
    categoryNumber: '2.4.3',
    questionNumber: '2.4.3.2',
    question: 'Is an applicant\'s gender a factor in hiring decisions?',
    progress: 100,
    completed: 1,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Discrimination',
    subsectionNumber: '2.4',
    category: 'Gender',
    categoryNumber: '2.4.3',
    questionNumber: '2.4.3.3',
    question: 'Is gender a factor in decisions regarding conditions of work?',
    progress: 100,
    completed: 1,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Discrimination',
    subsectionNumber: '2.4',
    category: 'Gender',
    categoryNumber: '2.4.3',
    questionNumber: '2.4.3.4',
    question: 'Is gender a factor in decisions regarding pay?',
    progress: 100,
    completed: 1,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Discrimination',
    subsectionNumber: '2.4',
    category: 'Gender',
    categoryNumber: '2.4.3',
    questionNumber: '2.4.3.5',
    question: 'Is gender a factor in decisions regarding opportunities for promotion or access to training?',
    progress: 100,
    completed: 1,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Discrimination',
    subsectionNumber: '2.4',
    category: 'Gender',
    categoryNumber: '2.4.3',
    questionNumber: '2.4.3.6',
    question: 'Is gender a factor in the employer\'s decisions regarding termination or retirement of workers?',
    progress: 100,
    completed: 1,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Discrimination',
    subsectionNumber: '2.4',
    category: 'Gender',
    categoryNumber: '2.4.3',
    questionNumber: '2.4.3.7',
    question: 'Are workers subject to sexual harassment?',
    progress: 100,
    completed: 1,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Discrimination',
    subsectionNumber: '2.4',
    category: 'Gender',
    categoryNumber: '2.4.3',
    questionNumber: '2.4.3.8',
    question: 'Does the employer require pregnancy tests or the use of contraceptives as a condition of employment?',
    progress: 100,
    completed: 1,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Discrimination',
    subsectionNumber: '2.4',
    category: 'Gender',
    categoryNumber: '2.4.3',
    questionNumber: '2.4.3.9',
    question: 'The maternity leave was excluded from workers\' period of continuous service?',
    progress: 100,
    completed: 1,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Discrimination',
    subsectionNumber: '2.4',
    category: 'Gender',
    categoryNumber: '2.4.3',
    questionNumber: '2.4.3.10',
    question: 'Does the employer change the employment status, position, wages, benefits or seniority of workers during or after maternity leave?',
    progress: 100,
    completed: 1,
    total: 1,
  },

  // 2.4.4 Other Grounds
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Discrimination',
    subsectionNumber: '2.4',
    category: 'Other Grounds',
    categoryNumber: '2.4.4',
    questionNumber: '2.4.4.1',
    question: 'Is an applicant\'s real or perceived HIV/AIDS status a factor in hiring decisions?',
    progress: 100,
    completed: 1,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Discrimination',
    subsectionNumber: '2.4',
    category: 'Other Grounds',
    categoryNumber: '2.4.4',
    questionNumber: '2.4.4.2',
    question: 'Are HIV/AIDS tests required at hiring or at any time during employment?',
    progress: 100,
    completed: 1,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Discrimination',
    subsectionNumber: '2.4',
    category: 'Other Grounds',
    categoryNumber: '2.4.4',
    questionNumber: '2.4.4.3',
    question: 'Is HIV/AIDS status a factor in decisions regarding conditions of work?',
    progress: 100,
    completed: 1,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Discrimination',
    subsectionNumber: '2.4',
    category: 'Other Grounds',
    categoryNumber: '2.4.4',
    questionNumber: '2.4.4.4',
    question: 'Is HIV/AIDS status a factor in decisions regarding pay?',
    progress: 100,
    completed: 1,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Discrimination',
    subsectionNumber: '2.4',
    category: 'Other Grounds',
    categoryNumber: '2.4.4',
    questionNumber: '2.4.4.5',
    question: 'Is HIV/AIDS status a factor in decisions regarding opportunities for promotion or access to training?',
    progress: 100,
    completed: 1,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Discrimination',
    subsectionNumber: '2.4',
    category: 'Other Grounds',
    categoryNumber: '2.4.4',
    questionNumber: '2.4.4.6',
    question: 'Is there harassment of workers on the basis of real or perceived HIV/AIDS status?',
    progress: 100,
    completed: 1,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Discrimination',
    subsectionNumber: '2.4',
    category: 'Other Grounds',
    categoryNumber: '2.4.4',
    questionNumber: '2.4.4.7',
    question: 'Is a worker\'s real or perceived HIV/AIDS status a factor in the employer\'s decisions regarding termination or retirement?',
    progress: 100,
    completed: 1,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Discrimination',
    subsectionNumber: '2.4',
    category: 'Other Grounds',
    categoryNumber: '2.4.4',
    questionNumber: '2.4.4.8',
    question: 'Are disabled persons who apply for work evaluated according to their ability to perform the job?',
    progress: 100,
    completed: 1,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Discrimination',
    subsectionNumber: '2.4',
    category: 'Other Grounds',
    categoryNumber: '2.4.4',
    questionNumber: '2.4.4.9',
    question: 'Has the employer taken steps to reasonably accommodate physically disabled persons?',
    progress: 100,
    completed: 1,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Discrimination',
    subsectionNumber: '2.4',
    category: 'Other Grounds',
    categoryNumber: '2.4.4',
    questionNumber: '2.4.4.10',
    question: 'Is disability a factor in decisions regarding conditions of work?',
    progress: 100,
    completed: 1,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Discrimination',
    subsectionNumber: '2.4',
    category: 'Other Grounds',
    categoryNumber: '2.4.4',
    questionNumber: '2.4.4.11',
    question: 'Is disability a factor in decisions regarding pay?',
    progress: 100,
    completed: 1,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Discrimination',
    subsectionNumber: '2.4',
    category: 'Other Grounds',
    categoryNumber: '2.4.4',
    questionNumber: '2.4.4.12',
    question: 'Is disability a factor in decisions regarding opportunities for promotion or access to training?',
    progress: 100,
    completed: 1,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Discrimination',
    subsectionNumber: '2.4',
    category: 'Other Grounds',
    categoryNumber: '2.4.4',
    questionNumber: '2.4.4.13',
    question: 'Is there harassment of workers on the basis of disability?',
    progress: 100,
    completed: 1,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Discrimination',
    subsectionNumber: '2.4',
    category: 'Other Grounds',
    categoryNumber: '2.4.4',
    questionNumber: '2.4.4.14',
    question: 'Is the employer\'s decisions regarding termination or retirement a factor of disability?',
    progress: 100,
    completed: 1,
    total: 1,
  },

  // 2.5 Forced Labour (categories collapsed in source — headers only with counts)
  // 2.5.1 Coercion — 100% (8/8)
  // 2.5.2 Bonded Labour — 100% (1/1)
  // 2.5.3 Forced Labour and Overtime — 100% (1/1)
  // 2.5.4 Prison Labour — 100% (1/1)
  // TODO: expand 2.5 categories to add individual question text

  // 2.6 Freedom of Association and Collective Bargaining
  // 2.6.1 Fact-Gathering Questions
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Freedom of Association and Collective Bargaining',
    subsectionNumber: '2.6',
    category: 'Fact-Gathering Questions',
    categoryNumber: '2.6.1',
    questionNumber: '2.6.1.1',
    question: 'What percentage of workers are union members?',
    progress: 0,
    completed: 0,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Freedom of Association and Collective Bargaining',
    subsectionNumber: '2.6',
    category: 'Fact-Gathering Questions',
    categoryNumber: '2.6.1',
    questionNumber: '2.6.1.2',
    question: 'How many active registered unions are there in the factory?',
    progress: 100,
    completed: 1,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Freedom of Association and Collective Bargaining',
    subsectionNumber: '2.6',
    category: 'Fact-Gathering Questions',
    categoryNumber: '2.6.1',
    questionNumber: '2.6.1.3',
    question: 'For each union, please provide name, last registration date, the number of union leaders (man, women), total number of members (men, women).',
    progress: 100,
    completed: 1,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Freedom of Association and Collective Bargaining',
    subsectionNumber: '2.6',
    category: 'Fact-Gathering Questions',
    categoryNumber: '2.6.1',
    questionNumber: '2.6.1.4',
    question: 'How many collective bargaining agreements are in effect in the factory?',
    progress: 100,
    completed: 1,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Freedom of Association and Collective Bargaining',
    subsectionNumber: '2.6',
    category: 'Fact-Gathering Questions',
    categoryNumber: '2.6.1',
    questionNumber: '2.6.1.5',
    question: 'For each CBA, please indicate the parties, the percentage of the workforce covered, the duration of the agreement.',
    progress: 100,
    completed: 1,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Freedom of Association and Collective Bargaining',
    subsectionNumber: '2.6',
    category: 'Fact-Gathering Questions',
    categoryNumber: '2.6.1',
    questionNumber: '2.6.1.6',
    question: 'How many strikes have there been since the last visit?',
    progress: 0,
    completed: 0,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Freedom of Association and Collective Bargaining',
    subsectionNumber: '2.6',
    category: 'Fact-Gathering Questions',
    categoryNumber: '2.6.1',
    questionNumber: '2.6.1.7',
    question: 'For each strike, please indicate the reason workers went on strike, whether the strike resulted in violence, the duration of the strike.',
    progress: 100,
    completed: 1,
    total: 1,
  },

  // 2.6.2 Freedom to Associate
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Freedom of Association and Collective Bargaining',
    subsectionNumber: '2.6',
    category: 'Freedom to Associate',
    categoryNumber: '2.6.2',
    questionNumber: '2.6.2.1',
    question: 'Can workers freely form and join a union?',
    progress: 100,
    completed: 1,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Freedom of Association and Collective Bargaining',
    subsectionNumber: '2.6',
    category: 'Freedom to Associate',
    categoryNumber: '2.6.2',
    questionNumber: '2.6.2.2',
    question: 'Can the union(s) freely form and join federations and confederations of their choice?',
    progress: 100,
    completed: 1,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Freedom of Association and Collective Bargaining',
    subsectionNumber: '2.6',
    category: 'Freedom to Associate',
    categoryNumber: '2.6.2',
    questionNumber: '2.6.2.3',
    question: 'Does the employer require workers to join a union?',
    progress: 100,
    completed: 1,
    total: 1,
  },

  // 2.6.3 Union Operations
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Freedom of Association and Collective Bargaining',
    subsectionNumber: '2.6',
    category: 'Union Operations',
    categoryNumber: '2.6.3',
    questionNumber: '2.6.3.1',
    question: 'Do union representatives have access to workers in the workplace?',
    progress: 100,
    completed: 1,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Freedom of Association and Collective Bargaining',
    subsectionNumber: '2.6',
    category: 'Union Operations',
    categoryNumber: '2.6.3',
    questionNumber: '2.6.3.2',
    question: 'Does the employer deduct union dues from wages when workers request this in writing?',
    progress: 100,
    completed: 1,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Freedom of Association and Collective Bargaining',
    subsectionNumber: '2.6',
    category: 'Union Operations',
    categoryNumber: '2.6.3',
    questionNumber: '2.6.3.3',
    question: 'Does the employer provide a place to post the names, positions, and activities of the union leaders?',
    progress: 100,
    completed: 1,
    total: 1,
  },

  // 2.6.4 Interference and Discrimination
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Freedom of Association and Collective Bargaining',
    subsectionNumber: '2.6',
    category: 'Interference and Discrimination',
    categoryNumber: '2.6.4',
    questionNumber: '2.6.4.1',
    question: 'Are workers free to meet without management present?',
    progress: 100,
    completed: 1,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Freedom of Association and Collective Bargaining',
    subsectionNumber: '2.6',
    category: 'Interference and Discrimination',
    categoryNumber: '2.6.4',
    questionNumber: '2.6.4.2',
    question: 'If there is more than one union, does the employer treat them equally?',
    progress: 100,
    completed: 1,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Freedom of Association and Collective Bargaining',
    subsectionNumber: '2.6',
    category: 'Interference and Discrimination',
    categoryNumber: '2.6.4',
    questionNumber: '2.6.4.3',
    question: 'Is the employer involved in union decision making, the formation of the constitution and rules, in union activities or the administration of the union?',
    progress: 100,
    completed: 0,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Freedom of Association and Collective Bargaining',
    subsectionNumber: '2.6',
    category: 'Interference and Discrimination',
    categoryNumber: '2.6.4',
    questionNumber: '2.6.4.4',
    question: 'Does the employer provide incentives to workers to keep them from joining a union or engaging in union activities?',
    progress: 100,
    completed: 0,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Freedom of Association and Collective Bargaining',
    subsectionNumber: '2.6',
    category: 'Interference and Discrimination',
    categoryNumber: '2.6.4',
    questionNumber: '2.6.4.5',
    question: 'Is a job applicant\'s union membership or union activities a factor in hiring decisions?',
    progress: 100,
    completed: 1,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Freedom of Association and Collective Bargaining',
    subsectionNumber: '2.6',
    category: 'Interference and Discrimination',
    categoryNumber: '2.6.4',
    questionNumber: '2.6.4.6',
    question: 'Has the employer taken steps to manipulate the union or to bring the union(s) under its control?',
    progress: 100,
    completed: 1,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Freedom of Association and Collective Bargaining',
    subsectionNumber: '2.6',
    category: 'Interference and Discrimination',
    categoryNumber: '2.6.4',
    questionNumber: '2.6.4.7',
    question: 'Does the employer punish workers for joining a union or engaging in union activities?',
    progress: 100,
    completed: 1,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Freedom of Association and Collective Bargaining',
    subsectionNumber: '2.6',
    category: 'Interference and Discrimination',
    categoryNumber: '2.6.4',
    questionNumber: '2.6.4.8',
    question: 'Does the employer threaten, intimidate, or harass workers who join a union or engage in union activities?',
    progress: 100,
    completed: 1,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Freedom of Association and Collective Bargaining',
    subsectionNumber: '2.6',
    category: 'Interference and Discrimination',
    categoryNumber: '2.6.4',
    questionNumber: '2.6.4.9',
    question: 'Has the employer terminated any worker or not renewed their contract due to the worker\'s union membership or union activities?',
    progress: 100,
    completed: 1,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Freedom of Association and Collective Bargaining',
    subsectionNumber: '2.6',
    category: 'Interference and Discrimination',
    categoryNumber: '2.6.4',
    questionNumber: '2.6.4.10',
    question: 'Has the employer terminated a union official without getting permission from the Ministry?',
    progress: 0,
    completed: 0,
    total: 1,
  },

  // 2.6.5 Collective Bargaining
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Freedom of Association and Collective Bargaining',
    subsectionNumber: '2.6',
    category: 'Collective Bargaining',
    categoryNumber: '2.6.5',
    questionNumber: '2.6.5.1',
    question: 'Does the employer consult with unions where legally required?',
    progress: 100,
    completed: 1,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Freedom of Association and Collective Bargaining',
    subsectionNumber: '2.6',
    category: 'Collective Bargaining',
    categoryNumber: '2.6.5',
    questionNumber: '2.6.5.2',
    question: 'Does the employer refuse to bargain collectively or refuse to bargain in good faith with the union, shop stewards or other worker representatives?',
    progress: 100,
    completed: 1,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Freedom of Association and Collective Bargaining',
    subsectionNumber: '2.6',
    category: 'Collective Bargaining',
    categoryNumber: '2.6.5',
    questionNumber: '2.6.5.3',
    question: 'If there is a collective bargaining agreement, are the provisions at least as favorable for workers as the law?',
    progress: 100,
    completed: 1,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Freedom of Association and Collective Bargaining',
    subsectionNumber: '2.6',
    category: 'Collective Bargaining',
    categoryNumber: '2.6.5',
    questionNumber: '2.6.5.4',
    question: 'Does the employer provide workers access to the collective bargaining agreements?',
    progress: 0,
    completed: 0,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Freedom of Association and Collective Bargaining',
    subsectionNumber: '2.6',
    category: 'Collective Bargaining',
    categoryNumber: '2.6.5',
    questionNumber: '2.6.5.5',
    question: 'Has the employer failed to implement any of the provisions of the collective bargaining agreement(s) in force?',
    progress: 100,
    completed: 1,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Freedom of Association and Collective Bargaining',
    subsectionNumber: '2.6',
    category: 'Collective Bargaining',
    categoryNumber: '2.6.5',
    questionNumber: '2.6.5.6',
    question: 'Has the employer tried to prevent any workers from participating in a strike?',
    progress: 100,
    completed: 1,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Freedom of Association and Collective Bargaining',
    subsectionNumber: '2.6',
    category: 'Collective Bargaining',
    categoryNumber: '2.6.5',
    questionNumber: '2.6.5.7',
    question: 'Has the employer hired new workers to replace striking workers during a strike?',
    progress: 100,
    completed: 1,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Freedom of Association and Collective Bargaining',
    subsectionNumber: '2.6',
    category: 'Collective Bargaining',
    categoryNumber: '2.6.5',
    questionNumber: '2.6.5.8',
    question: 'Has the employer punished any workers for participating in a strike?',
    progress: 100,
    completed: 1,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Freedom of Association and Collective Bargaining',
    subsectionNumber: '2.6',
    category: 'Collective Bargaining',
    categoryNumber: '2.6.5',
    questionNumber: '2.6.5.9',
    question: 'Were security guards, the police or armed forces called by the employer to break up a peaceful strike or assembly?',
    progress: 100,
    completed: 1,
    total: 1,
  },

  // 2.7 Compensation
  // 2.7.1 Minimum Wages/Piece Rate Wages
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Compensation',
    subsectionNumber: '2.7',
    category: 'Minimum Wages/Piece Rate Wages',
    categoryNumber: '2.7.1',
    questionNumber: '2.7.1.1',
    question: 'Does the employer pay at least minimum wage for ordinary hours of work to regular full-time workers?',
    progress: 0,
    completed: 0,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Compensation',
    subsectionNumber: '2.7',
    category: 'Minimum Wages/Piece Rate Wages',
    categoryNumber: '2.7.1',
    questionNumber: '2.7.1.2',
    question: 'Does the employer pay piece rate workers correctly for ordinary hours of work when their piece rate earnings fall below the minimum wage?',
    progress: 100,
    completed: 1,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Compensation',
    subsectionNumber: '2.7',
    category: 'Minimum Wages/Piece Rate Wages',
    categoryNumber: '2.7.1',
    questionNumber: '2.7.1.3',
    question: 'Does the employer pay at least minimum wage for all types of workers other than regular workers?',
    progress: 100,
    completed: 1,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Compensation',
    subsectionNumber: '2.7',
    category: 'Minimum Wages/Piece Rate Wages',
    categoryNumber: '2.7.1',
    questionNumber: '2.7.1.4',
    question: 'Is the piece rate set at a level that permits workers of average ability working normal hours to earn minimum wage?',
    progress: 100,
    completed: 1,
    total: 1,
  },

  // 2.7.2 Overtime Wages
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Compensation',
    subsectionNumber: '2.7',
    category: 'Overtime Wages',
    categoryNumber: '2.7.2',
    questionNumber: '2.7.2.1',
    question: 'Does the employer pay workers 150% of their normal wage for all ordinary overtime hours worked?',
    progress: 100,
    completed: 1,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Compensation',
    subsectionNumber: '2.7',
    category: 'Overtime Wages',
    categoryNumber: '2.7.2',
    questionNumber: '2.7.2.2',
    question: 'Does the employer pay workers double their normal wage for all overtime hours worked at night?',
    progress: 100,
    completed: 1,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Compensation',
    subsectionNumber: '2.7',
    category: 'Overtime Wages',
    categoryNumber: '2.7.2',
    questionNumber: '2.7.2.3',
    question: 'Does the employer pay workers double their normal wage for all hours worked on weekly rest days?',
    progress: 100,
    completed: 1,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Compensation',
    subsectionNumber: '2.7',
    category: 'Overtime Wages',
    categoryNumber: '2.7.2',
    questionNumber: '2.7.2.4',
    question: 'Does the employer pay all workers correctly for work on public holidays?',
    progress: 100,
    completed: 1,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Compensation',
    subsectionNumber: '2.7',
    category: 'Overtime Wages',
    categoryNumber: '2.7.2',
    questionNumber: '2.7.2.5',
    question: 'Does the employer pay all workers the correct meal allowance or give them a reasonable free meal when they work overtime?',
    progress: 100,
    completed: 1,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Compensation',
    subsectionNumber: '2.7',
    category: 'Overtime Wages',
    categoryNumber: '2.7.2',
    questionNumber: '2.7.2.6',
    question: 'Does the employer pay workers 130% of their normal wage for regular working hours worked at night?',
    progress: 100,
    completed: 1,
    total: 1,
  },

  // 2.7.3 Method of Payment
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Compensation',
    subsectionNumber: '2.7',
    category: 'Method of Payment',
    categoryNumber: '2.7.3',
    questionNumber: '2.7.3.1',
    question: 'Are workers paid on time, twice per month?',
    progress: 100,
    completed: 1,
    total: 1,
  },
  {
    section: 'ILO',
    sectionNumber: '2',
    subsection: 'Compensation',
    subsectionNumber: '2.7',
    category: 'Method of Payment',
    categoryNumber: '2.7.3',
    questionNumber: '2.7.3.2',
    question: 'Are workers\' full wages paid in the manner required (in cash, during working hours, at the workplace, and in legal tender)?',
    progress: 100,
    completed: 1,
    total: 1,
  },
];

async function seed() {
  try {
    await mongoose.connect(process.env.MONGODB_URI);
    console.log('Connected to MongoDB');

    await ChecklistItem.deleteMany({ section: 'ILO' });
    console.log('Cleared existing ILO checklist items');

    const result = await ChecklistItem.insertMany(iloQuestions);
    console.log(`Inserted ${result.length} checklist items`);

    await mongoose.disconnect();
    console.log('Done!');
  } catch (err) {
    console.error('Seed error:', err);
    process.exit(1);
  }
}

seed();
